from BaseClasses import Item

class AE2Item(Item):
	game: str = "Ape Escape 2"

item_id_from_name: dict[str, int] = {
	#Gadgets
	"Monkey Net": 1,
	"Stun Club": 2,
	"Monkey Radar": 3,
	"Water Net": 4,
	"Dash Hoop": 5,
	"Catapult": 6,
	"Sky Flyer": 7,
	"R.C. Car": 8,
	"Bananarang": 9,
	"Water Cannon": 10,
	"Electro Magnet": 11,
	"Power Punch": 12,
	"Pipotchi": 13,
	"See-All Scope": 14,
	"Progressive Catapult": 15,

	#Progression
	"World Key": 101,
	"Victory": 102,
	"Gotcha Box Restock": 103,

	#Filler
	"Jacket": 201,
	"Cookie": 202,
	"Deluxe Cookie": 203,
	"Explosive Pellet": 204,
	"Guided Pellet": 205,
	"Gold Coin": 206,
	"10 Gold Coins": 207,
	"20 Gold Coins": 208,
	"3 Explosive Pellets": 209,
	"3 Guided Pellets": 210,

	#Abilities
	"Air Crawl": 300,

	#Traps
	"Lazy Camera Trap": 400,
	"Rocket Boots Trap": 401,
	"Slowness Trap": 402,

	#Other
	"Glitched Item": 500,

	#Gotcha Box Unlockables
	'Monkey Football': 1000,
	'Dance, Monkey, Dance!': 1001,
	'Monkey Climber': 1002,

	'Black R.C. Car Body': 1003,
	'Tissues R.C. Car Body': 1004,
	'Sushi R.C. Car Body': 1005,
	'Pudding R.C. Car Body': 1006,

	'Monkey Fable: "Monkey Taro"': 1007,
	'Monkey Fable: "Monkey Taro II"': 1008,
	'Monkey Fable: "The Monkey Who Cried Hikaru"': 1009,
	'Monkey Fable: "Monkerella"': 1010,
	'Monkey Fable: "Apeshima Taro"': 1011,
	'Monkey Fable: "The Grateful Monkey"': 1012,
	'Monkey Fable: "The Wise Monkey"': 1013,
	'Monkey Fable: "Little Red Monkey Helmet"': 1014,
	'Monkey Fable: "Monkerella II"': 1015,
	'Monkey Fable: "The Monkey Statue"': 1016,
	'Monkey Fable: "The Gold and Silver Bananas"': 1017,
	'Monkey Fable: "The Never Ending Banana"': 1018,
	'Monkey Fable: "The Monkey Village"': 1019,
	'Monkey Fable: "The Three Little Monkeys"': 1020,
	'Monkey Fable: "Jack and the Bananastalk"': 1021,
	'Monkey Fable: "Hikaru and Pipotchi"': 1022,
	'Monkey Fable: "Thumbelotchi"': 1023,
	'Monkey Fable: "The Monkey\'s New Clothes"': 1024,
	'Monkey Fable: "The Giant Bananastalk"': 1025,
	'Monkey Fable: "Nightmare Scenario"': 1026,

	'Movie: "Monkeys on Parade"': 1027,
	'Movie: "The Beginning"': 1028,
	'Movie: "Meet Specter"': 1029,
	'Movie: "Hikaru and the Professor"': 1030,
	'Movie: "It\'s Giant Yellow Monkey!"': 1031,
	'Movie: "Battle with Specter!"': 1032,
	'Movie: "Final Battle with Specter!"': 1033,
	'Movie: "Escape the Ape in You!"': 1034,

	'Soundtrack: "Theme Tune"': 1035,
	'Soundtrack: "Monkeys On Parade!"': 1036,
	'Soundtrack: "The Beginning"': 1037,
	'Soundtrack: "Liberty Island"': 1038,
	'Soundtrack: "Breezy Village"': 1039,
	'Soundtrack: "Port Calm"': 1040,
	'Soundtrack: "Viva Apespania!"': 1041,
	'Soundtrack: "Castle Frightmare"': 1042,
	'Soundtrack: "Vita-Z Factory"': 1043,
	'Soundtrack: "Casino City"': 1044,
	'Soundtrack: "Ninja Hideout"': 1045,
	'Soundtrack: "Snowball Mountain"': 1046,
	'Soundtrack: "Snowball Ski Slope"': 1047,
	'Soundtrack: "Lookout Valley"': 1048,
	'Soundtrack: "The Blue Baboon"': 1049,
	'Soundtrack: "Enter the Monkey"': 1050,
	'Soundtrack: "Simian Citadel"': 1051,
	'Soundtrack: "Panic Pyramid"': 1052,
	'Soundtrack: "Pirate Isle"': 1053,
	'Soundtrack: "Land of the Apes"': 1054,
	'Soundtrack: "Monkey Hot Springs"': 1055,
	'Soundtrack: "Monkey Ski Slope"': 1056,
	'Soundtrack: "The Lost World"': 1057,
	'Soundtrack: "Skyscraper City"': 1058,
	'Soundtrack: "Code C.H.I.M.P."': 1059,
	'Soundtrack: "Code C.H.I.M.P. II"': 1060,
	'Soundtrack: "Moon Base 1"': 1061,
	'Soundtrack: "Moon Base 2"': 1062,
	'Soundtrack: "Scheming Specter"': 1063,
	'Soundtrack: "Song of the Freaky Monkey Five"': 1064,
	'Soundtrack: "Escape the Ape in You!"': 1065,
	'Soundtrack: "Freaky Monkey Five Battle!"': 1066,
	'Soundtrack: "Giant Yellow Monkey Battle!"': 1067,
	'Soundtrack: "Battle with Specter!"': 1068,
	'Soundtrack: "Specter\'s Theme"': 1069,
	'Soundtrack: "Final Battle with Specter!"': 1070,
	'Soundtrack: "Ending 1"': 1071,
	'Soundtrack: "Ending 2"': 1072,
	'Soundtrack: "Staff Credits"': 1073,
	'Soundtrack: "Travel Station"': 1074,
	'Soundtrack: "Gadget Trainer"': 1075,
	'Soundtrack: "New Gotcha Gadget!"': 1076,
	'Soundtrack: "Stage Cleared!"': 1077,
	'Soundtrack: "Stage Perfectly Cleared!"': 1078,
	'Soundtrack: "Monkey Football!"': 1079,
	'Soundtrack: "Kick Off!"': 1080,
	'Soundtrack: "Gotcha Rhythm"': 1081,
	'Soundtrack: "Monkeys\' Gonna Getchu!"': 1082,
	'Soundtrack: "Monkey Chorus"': 1083,
	'Soundtrack: "Monkey Climber"': 1084,

	'Comic Strip: "An Extra Slice"': 1085,
	'Comic Strip: "The Scent of Banana"': 1086,
	'Comic Strip: "Girl Hunting"': 1087,
	'Comic Strip: "The Leak in the Roof"': 1088,
	'Comic Strip: "The Little Matchstick Girl"': 1089,
	'Comic Strip: "Multi-Purpose Stun Club"': 1090,
	'Comic Strip: "The Bowling Tournament"': 1091,
	'Comic Strip: "First Day of School"': 1092,
	'Comic Strip: "Birth of an Enemy"': 1093,
	'Comic Strip: "An Amazing Magic Show"': 1094,
	'Comic Strip: "A Completely Sealed Room"': 1095,
	'Comic Strip: "The Race"': 1096,
	'Comic Strip: "Missing Weapon"': 1097,
	'Comic Strip: "Ms. Banana is Saved!"': 1098,
	'Comic Strip: "Spinning Specs"': 1099,
	'Comic Strip: "Monkey Test"': 1100,
	'Comic Strip: "Safety Precautions"': 1101,

	'Concept Artwork: "Freaky Monkey Five"': 1102,
	'Concept Artwork: "Blue Monkey"': 1103,
	'Concept Artwork: "Yellow Monkey"': 1104,
	'Concept Artwork: "Pink Monkey"': 1105,
	'Concept Artwork: "White Monkey"': 1106,
	'Concept Artwork: "Red Monkey"': 1107,
	'Concept Artwork: "Hikaru 1"': 1108,
	'Concept Artwork: "Pipotchi 1"': 1109,
	'Concept Artwork: "Hikaru and Pipotchi 1"': 1110,
	'Concept Artwork: "Natsumi 1"': 1111,
	'Concept Artwork: "Professor 1"': 1112,
	'Concept Artwork: "Expression 1"': 1113,
	'Concept Artwork: "Expression 2"': 1114,
	'Concept Artwork: "Pipotchi 2"': 1115,
	'Concept Artwork: "Pipotchi 3"': 1116,
	'Concept Artwork: "Pipotchi 4"': 1117,
	'Concept Artwork: "Hikaru 2"': 1118,
	'Concept Artwork: "Hikaru 3"': 1119,
	'Concept Artwork: "Hikaru and Pipotchi 2"': 1120,
	'Concept Artwork: "Hikaru 4"': 1121,
	'Concept Artwork: "Hikaru 5"': 1122,
	'Concept Artwork: "Hikaru 6"': 1123,
	'Concept Artwork: "Hikaru 7"': 1124,
	'Concept Artwork: "Hikaru and Pipotchi 3"': 1125,
	'Concept Artwork: "Hikaru 8"': 1126,
	'Concept Artwork: "Hikaru 9"': 1127,
	'Concept Artwork: "Hikaru and Pipotchi 4"': 1128,
	'Concept Artwork: "Hikaru 10"': 1129,
	'Concept Artwork: "Pipotchi 5"': 1130,
	'Concept Artwork: "Pipotchi 6"': 1131,
	'Concept Artwork: "Pipotchi 7"': 1132,
	'Concept Artwork: "Natsumi 2"': 1133,
	'Concept Artwork: "Hikaru 11"': 1134,
	'Concept Artwork: "Kakeru"': 1135,
	'Concept Artwork: "Hiroki"': 1136,
	'Concept Artwork: "Charu 1"': 1137,
	'Concept Artwork: "Charu 2"': 1138,
	'Concept Artwork: "Charu 3"': 1139,
	'Concept Artwork: "Charu 4"': 1140,
	'Concept Artwork: "The Professor 2"': 1141,
	'Concept Artwork: "Stage Settings 1"': 1142,
	'Concept Artwork: "Stage Settings 2"': 1143,
	'Concept Artwork: "Stage Settings 3"': 1144,
	'Concept Artwork: "Stage Settings 4"': 1145,
	'Concept Artwork: "Stage Settings 5"': 1146,
	'Concept Artwork: "Stage Settings 6"': 1147,
	'Concept Artwork: "Stage Settings 7"': 1148,
	'Concept Artwork: "Stage Settings 8"': 1149,
	'Concept Artwork: "Stage Settings 9"': 1150,
	'Concept Artwork: "Stage Settings 10"': 1151,

	'Secret Photo: "The Three Afro Brothers"': 1152,
	'Secret Photo: "Rock-Paper-Scissors Tournament"': 1153,
	'Secret Photo: "You beast!"': 1154,
	'Secret Photo: "Festival in the Forest"': 1155,
	'Secret Photo: "Fruits of Training"': 1156,
	'Secret Photo: "Oh my?!"': 1157,
	'Secret Photo: "Quite Close Friends"': 1158,
	'Secret Photo: "Give It All You\'ve Got"': 1159,
	'Secret Photo: "Happy Banana Gang"': 1160,
	'Secret Photo: "This Year\'s Style"': 1161,
	'Secret Photo: "Toilet Incident"': 1162,
	'Secret Photo: "Photo of Two"': 1163,
	'Secret Photo: "Almighty? Ski Gang"': 1164,
	'Secret Photo: "Dry Throat"': 1165,
	'Secret Photo: "Nice One"': 1166,
	'Secret Photo: "Advanced RC Car"': 1167,
	'Secret Photo: "Debut Concert"': 1168,
	'Secret Photo: "Program Input"': 1169,
	'Secret Photo: "Ape World Champion"': 1170,
	'Secret Photo: "Ultra Goliath Armour"': 1171,
	'Secret Photo: "Specter\'s Entrance"': 1172,
	'Secret Photo: "Advanced Strategy?"': 1173,
	'Secret Photo: "Monkey Cannon"': 1174,
	'Secret Photo: "Monkey UFO"': 1175,
	'Secret Photo: "RoboCow"': 1176,
	'Secret Photo: "\'Banana Buffet\' research"': 1177,
	'Secret Photo: "RoboApe"': 1178,
	'Secret Photo: "Legendary Captain"': 1179,
	'Secret Photo: "Quite a photo, eh?"': 1180,
	'Secret Photo: "Sauna, anyone?"': 1181,
	'Secret Photo: "Advanced Sky Flyer"': 1182,
	'Secret Photo: "Everyone gather together!"': 1183,
	'Secret Photo: "Robo Kong"': 1184,
	'Secret Photo: "I\'ll never let you go..."': 1185,
	'Secret Photo: "Gotcha!"': 1186,
	'Secret Photo: "Get both of them!"': 1187,
	'Secret Photo: "I\'m staying right here."': 1188,
	'Secret Photo: "Monkey VS Pudding"': 1189,
	'Secret Photo: "Monkey Statue of Liberty"': 1190,
	'Secret Photo: "The Last Straw"': 1191,
	'Secret Photo: "Break the sound barrier!"': 1192,
	'Secret Photo: "Monkey Sauna"': 1193,
	'Secret Photo: "You Are the Driver"': 1194,
	'Secret Photo: "Underwater Rendezvous"': 1195,
	'Secret Photo: "Ultimate Confrontation"': 1196,
	'Secret Photo: "There\'s no stopping"': 1197,
	'Secret Photo: "You\'re not bad!"': 1198,
	'Secret Photo: "We\'re not friends anymore?"': 1199,
	'Secret Photo: "Get a home run"': 1200,
	'Secret Photo: "Out for Blood!"': 1201,

	'Enemy Photo: "Porky"': 1202,
	'Enemy Photo: "Blue Porky"': 1203,
	'Enemy Photo: "Armoured Porky"': 1204,
	'Enemy Photo: "Skeleton Swine"': 1205,
	'Enemy Photo: "Mohawk Porky"': 1206,
	'Enemy Photo: "Tank Porky"': 1207,
	'Enemy Photo: "Tank Piglet"': 1208,
	'Enemy Photo: "Flame Porky"': 1209,
	'Enemy Photo: "Tomato Bird"': 1210,
	'Enemy Photo: "Eggplant Bee"': 1211,
	'Enemy Photo: "Pineapple Finch"': 1212,
	'Enemy Photo: "AAA Jellyfish"': 1213,
	'Enemy Photo: "Wax Owl"': 1214,
	'Enemy Photo: "Wax Queen"': 1215,
	'Enemy Photo: "Charred Chester"': 1216,
	'Enemy Photo: "They Might Be Slime"': 1217,
	'Enemy Photo: "Lousy rat"': 1218,
	'Enemy Photo: "Pinguin"': 1219,
	'Enemy Photo: "Boney M"': 1220,
	'Enemy Photo: "Sky Bomber"': 1221,
	'Enemy Photo: "Barbell Bomber"': 1222,
	'Enemy Photo: "Puffy the Blowfish"': 1223,
	'Enemy Photo: "Grinning Piranha"': 1224,
	'Enemy Photo: "The Bombettes"': 1225,
	'Enemy Photo: "Space Can"': 1226,
	'Enemy Photo: Submarine Lookalike""': 1227,
	'Enemy Photo: "Robo Kong"': 1228,

	'Stage Photo: "Liberty Park"': 1229,
	'Stage Photo: "Breezy Village"': 1230,
	'Stage Photo: "Port Calm"': 1231,
	'Stage Photo: "Viva Apespania!"': 1232,
	'Stage Photo: "Castle Frightmare"': 1233,
	'Stage Photo: "Vita-Z Factory"': 1234,
	'Stage Photo: "Casino City"': 1235,
	'Stage Photo: "Ninja Hideout"': 1236,
	'Stage Photo: "Snowball Mountain"': 1237,
	'Stage Photo: "Lookout Valley"': 1238,
	'Stage Photo: "The Blue Baboon"': 1239,
	'Stage Photo: "Enter the Monkey"': 1240,
	'Stage Photo: "Simian Citadel"': 1241,
	'Stage Photo: "Panic Pyramid"': 1242,
	'Stage Photo: "Pirate Isle"': 1243,
	'Stage Photo: "Land of the Apes"': 1244,
	'Stage Photo: "The Lost World"': 1245,
	'Stage Photo: "Skyscraper City"': 1246,
	'Stage Photo: "Code C.H.I.M.P."': 1247,
	'Stage Photo: "Moon Base"': 1248
}

gadget_aliases = {
	"Net": "Monkey Net",
	"Time Net": "Monkey Net",
	"Club": "Stun Club",
	"Radar": "Monkey Radar",
	"Hoop": "Dash Hoop",
	"Super Hoop": "Dash Hoop",
	"Sling": "Catapult",
	"Slingshot": "Catapult",
	"Slingback Shooter": "Catapult",
	"Slingback": "Catapult",
	"Flyer": "Sky Flyer",
	"RC Car": "R.C. Car",
	"Car": "R.C. Car",
	"Magnet": "Electro Magnet",
	"Magic Punch": "Power Punch",
	"Punch": "Power Punch"
}

item_name_from_id: dict[int, str] = {v: k for k, v in item_id_from_name.items()}