from dataclasses import dataclass, field

@dataclass
class Monkey:
    name: str
    level: str
    address: dict = field(default_factory = dict)
    connection_requirements: dict[str, list[str]] = field(default_factory = lambda: {"Entry from Spawn": [[]]})
    room: str = "Entry"
    
    def get_location_name(self):
        if self.room == "Entry":
            return self.level + ": " + self.name.strip(" ")
        else:
            return self.level + " (" + self.room + "): " + self.name.strip(" ")

monkeys = [
    #Liberty Island
    Monkey(name = "George", level = "Liberty Island", address = {"PAL": 0x3E1A69, "NTSC": 0x3E0759}),
    Monkey(name = "Libby", level = "Liberty Island", address = {"PAL": 0x3E1A6B, "NTSC": 0x3E075B}),
    Monkey(name = "Tomkey Cruise", level = "Liberty Island", address = {"PAL": 0x3E1A6E, "NTSC": 0x3E075E}),
    Monkey(name = "Chill", level = "Liberty Island", address = {"PAL": 0x3E1A6C, "NTSC": 0x3E075C}),
    Monkey(name = "Henry", level = "Liberty Island", address = {"PAL": 0x3E1A6D, "NTSC": 0x3E075D}, connection_requirements = {"Entry from Spawn": [["Catapult"]]}),
    Monkey(name = "Harley Q. Win", level = "Liberty Island", address = {"PAL": 0x3E1ABC, "NTSC": 0x3E07AC}, connection_requirements = {"Entry from Spawn": [["*Punch"]]}),

    #Breezy Village
    Monkey(name = "Dozy", level = "Breezy Village", address = {"PAL": 0x3E1A73, "NTSC": 0x3E0763}, connection_requirements = {"Entry from Spawn": [["*Radar", "*Attack"], ["*Hard"]]}),
    Monkey(name = "Baboondini", level = "Breezy Village", address = {"PAL": 0x3E1A74, "NTSC": 0x3E0764}),
    Monkey(name = "Walter", level = "Breezy Village", address = {"PAL": 0x3E1A6F, "NTSC": 0x3E075F}),
    Monkey(name = "Jon", level = "Breezy Village", address = {"PAL": 0x3E1A70, "NTSC": 0x3E0760}, connection_requirements = {"Entry from Spawn": [["*Radar", "*Attack"], ["*Hard"]]}),
    Monkey(name = "Crusty", level = "Breezy Village", address = {"PAL": 0x3E1A72, "NTSC": 0x3E0762}),
    Monkey(name = "Balboa", level = "Breezy Village", address = {"PAL": 0x3E1A75, "NTSC": 0x3E0765}, connection_requirements = {"Entry from Spawn": [["*Punch"]]}),

    #Port Calm
    Monkey(name = "Dannyboy", level = "Port Calm", address = {"PAL": 0x3E1A76, "NTSC": 0x3E0766}, connection_requirements = {"Entry from Spawn": [["Water Net"], ["*Air Crawl"], ["Sky Flyer", "*Hard"], ["*Expert"]], "Entry from Indoors": [["Water Net"]]}),
    Monkey(name = "Seanyboy", level = "Port Calm", address = {"PAL": 0x3E1A79, "NTSC": 0x3E0769}, connection_requirements = {"Entry from Spawn": [["Water Net"], ["*Air Crawl"], ["Sky Flyer", "*Hard"], ["*Expert"]], "Entry from Indoors": [["Water Net"]]}),
    Monkey(name = "Chili", level = "Port Calm", address = {"PAL": 0x3E1A77, "NTSC": 0x3E0767}, connection_requirements = {"Entry from Spawn": [["Water Net"], ["*Air Crawl"], ["Sky Flyer", "*Hard"], ["*Expert"]], "Entry from Indoors": [["Water Net"]]}),
    Monkey(name = "Beday", level = "Port Calm", address = {"PAL": 0x3E1A7A, "NTSC": 0x3E076A}, connection_requirements = {"Entry from Spawn": [["Water Net", "*Attack"], ["*Air Crawl"], ["Sky Flyer", "*Hard"], ["*Long Jump", "*Expert"], ["Pipotchi", "*Expert"]], "Entry from Indoors": [["Water Net"]]}),
    Monkey(name = "Florence", level = "Port Calm", address = {"PAL": 0x3E1A78, "NTSC": 0x3E0768}, connection_requirements = {"Entry from Spawn": [["Water Net"], ["*Air Crawl", "*Hard"], ["*Expert"]], "Entry from Indoors": [["Water Net"]]}),
    Monkey(name = "Punto", level = "Port Calm", address = {"PAL": 0x3E1A7B, "NTSC": 0x3E076B}, connection_requirements = {"Entry from Spawn": [["Water Net"], ["Sky Flyer", "*Hard"], ["*Air Crawl", "*Hard"], ["*Expert"]], "Entry from Indoors": [["Water Net"]]}),
    Monkey(name = "Lilo", level = "Port Calm", room = "Indoors", address = {"PAL": 0x3E1A7C, "NTSC": 0x3E076C}, connection_requirements = {"Indoors from Entry": [["Water Net"]]}),
    Monkey(name = "Manuel", level = "Port Calm", room = "Indoors", address = {"PAL": 0x3E1A7D, "NTSC": 0x3E076D}, connection_requirements = {"Indoors from Entry": [["Water Net", "*Punch"]]}),

    #Viva Apespania
    Monkey(name = "Pogo", level = "Viva Apespania", address = {"PAL": 0x3E1A7F, "NTSC": 0x3E076F}, connection_requirements = {"Entry from Spawn": [["*Radar", "*Attack"], ["*Hard"]], "Entry from Village": [["*Radar", "*Attack"], ["*Hard"]]}),
    Monkey(name = "Slope", level = "Viva Apespania", address = {"PAL": 0x3E1A7E, "NTSC": 0x3E076E}, connection_requirements = {"Entry from Spawn": [["Dash Hoop"], ["Sky Flyer", "*Hard"], ["*Air Crawl"]], "Entry from Village": [["Dash Hoop"], ["Sky Flyer", "*Hard"], ["*Air Crawl"]]}),
    Monkey(name = "Billy", level = "Viva Apespania", address = {"PAL": 0x3E1A80, "NTSC": 0x3E0770}, connection_requirements = {"Entry from Spawn": [["Dash Hoop"], ["*Hard"]], "Entry from Village": [["Dash Hoop"], ["*Hard"]]}),
    Monkey(name = "Ole", level = "Viva Apespania", room = "Village", address = {"PAL": 0x3E1AE5, "NTSC": 0x3E07D5}, connection_requirements = {"Village from Entry": [[]], "Village from Bullring": [[]]}),
    Monkey(name = "Chutney", level = "Viva Apespania", room = "Village", address = {"PAL": 0x3E1A86, "NTSC": 0x3E0776}, connection_requirements = {"Village from Entry": [["*Attack"], ["*Hard"]], "Village from Bullring": [["*Attack"], ["*Hard"]]}),
    Monkey(name = "Wiz", level = "Viva Apespania", room = "Village", address = {"PAL": 0x3E1A81, "NTSC": 0x3E0771}, connection_requirements = {"Village from Entry": [["Dash Hoop"], ["*Hard"]], "Village from Bullring": [["Dash Hoop"], ["*Hard"]]}),
    Monkey(name = "Birgit", level = "Viva Apespania", room = "Village", address = {"PAL": 0x3E1A83, "NTSC": 0x3E0773}, connection_requirements = {"Village from Entry": [["Dash Hoop"], ["Sky Flyer", "*Hard"], ["*Air Crawl"]], "Village from Bullring": [["Dash Hoop"], ["Sky Flyer", "*Hard"], ["*Air Crawl"]]}),
    Monkey(name = "Lily", level = "Viva Apespania", room = "Village", address = {"PAL": 0x3E1A82, "NTSC": 0x3E0772}, connection_requirements = {"Village from Entry": [["*Attack"], ["*Hard"]], "Village from Bullring": [["*Attack"], ["*Hard"]]}),
    Monkey(name = "Trip", level = "Viva Apespania", room = "Village", address = {"PAL": 0x3E1A84, "NTSC": 0x3E0774}, connection_requirements = {"Village from Entry": [["Dash Hoop"], ["*Hard"]], "Village from Bullring": [[]]}),
    Monkey(name = "Toro", level = "Viva Apespania", room = "Bullring", address = {"PAL": 0x3E1A88, "NTSC": 0x3E0778}, connection_requirements = {"Bullring from Village": [["Dash Hoop"], ["Catapult", "*Hard"], ["Sky Flyer", "*Hard"]]}),
    Monkey(name = "Annie", level = "Viva Apespania", room = "Bullring", address = {"PAL": 0x3E1A87, "NTSC": 0x3E0777}, connection_requirements = {"Bullring from Village": [["Dash Hoop", "*Bull Fight"], ["Catapult", "*Hard", "*Bull Fight"], ["Sky Flyer", "*Hard", "*Bull Fight"]]}),
    Monkey(name = "Luis", level = "Viva Apespania", room = "Bullring", address = {"PAL": 0x3E1A85, "NTSC": 0x3E0775}, connection_requirements = {"Bullring from Village": [["*Punch"]]}),

    #Blue Monkey Battle!
    Monkey(name = "Blue Monkey", level = "Blue Monkey Battle!", address = {"PAL": 0x3E1BA8, "NTSC": 0x3E0898}, connection_requirements = {"Entry from Spawn": [["*Attack"], ["Catapult"], ["R.C. Car", "*Hard"], ["Bananarang", "*Hard"], ["*Expert"]]}),

    #Castle Frightmare
    Monkey(name = "Arthur", level = "Castle Frightmare", address = {"PAL": 0x3E1AC8, "NTSC": 0x3E07B8}, connection_requirements = {"Entry from Spawn": [["*Punch"]], "Entry from House": [["*Punch"]]}),
    Monkey(name = "Virgil", level = "Castle Frightmare", address = {"PAL": 0x3E1AE1, "NTSC": 0x3E07D1}, connection_requirements = {"Entry from Spawn": [["*Radar", "*Attack"], ["*Hard"]], "Entry from House": [["*Radar", "*Attack"], ["*Hard"]]}),
    Monkey(name = "The Invisible Monkey", level = "Castle Frightmare", room = "Inside", address = {"PAL": 0x3E1A8F, "NTSC": 0x3E077F}, connection_requirements = {"House from Entry": [["*Punch", "Water Cannon"], ["*Punch", "*Damage Boost", "*Hard"]], "House from Dungeon": [["*Punch", "Water Cannon"], ["*Punch", "*Damage Boost", "*Hard"]]}),
    Monkey(name = "Monk Quixote", level = "Castle Frightmare", room = "Inside", address = {"PAL": 0x3E1A8A, "NTSC": 0x3E077A}, connection_requirements = {"House from Entry": [["*Attack"], ["*Hard"]], "House from Dungeon": [["*Attack"], ["*Hard"]]}),
    Monkey(name = "Van", level = "Castle Frightmare", room = "Inside", address = {"PAL": 0x3E1A8B, "NTSC": 0x3E077B}, connection_requirements = {"House from Entry": [["*Attack"], ["*Hard", "*Non-Net"]], "House from Dungeon": [["*Attack"], ["*Hard", "*Non-Net"]]}),
    Monkey(name = "Simon", level = "Castle Frightmare", room = "Inside", address = {"PAL": 0x3E1A8C, "NTSC": 0x3E077C}, connection_requirements = {"House from Entry": [["*Attack"], ["*Hard"]], "House from Dungeon": [["*Attack"], ["*Hard"]]}),
    Monkey(name = "Pierce", level = "Castle Frightmare", room = "Inside", address = {"PAL": 0x3E1A8E, "NTSC": 0x3E077E}, connection_requirements = {"House from Entry": [["*Attack"], ["*Hard"]], "House from Dungeon": [["*Attack"], ["*Hard"]]}),
    Monkey(name = "Jumpy", level = "Castle Frightmare", room = "Inside", address = {"PAL": 0x3E1A91, "NTSC": 0x3E0781}, connection_requirements = {"House from Entry": [["*Attack"], ["*Hard"]], "House from Dungeon": [["*Attack"], ["*Hard"]]}),
    Monkey(name = "Viv", level = "Castle Frightmare", room = "Inside", address = {"PAL": 0x3E1A89, "NTSC": 0x3E0779}, connection_requirements = {"House from Entry": [[]], "House from Dungeon": [[]]}),
    Monkey(name = "Count Monkula", level = "Castle Frightmare", room = "Inside", address = {"PAL": 0x3E1A8D, "NTSC": 0x3E077D}, connection_requirements = {"House from Entry": [[]], "House from Dungeon": [[]]}),
    Monkey(name = "Hyde", level = "Castle Frightmare", room = "Dungeon", address = {"PAL": 0x3E1B25, "NTSC": 0x3E0815}, connection_requirements = {"Dungeon from House": [[]]}),
    Monkey(name = "Stein", level = "Castle Frightmare", room = "Dungeon", address = {"PAL": 0x3E1A92, "NTSC": 0x3E0782}, connection_requirements = {"Dungeon from House": [["Stun Club"], ["Power Punch"], ["Catapult"], ["*Hard"]]}),
    Monkey(name = "Nana", level = "Castle Frightmare", room = "Dungeon", address = {"PAL": 0x3E1A90, "NTSC": 0x3E0780}, connection_requirements = {"Dungeon from House": [[]]}),

    #Vita-Z Factory
    Monkey(name = "Vic", level = "Vita-Z Factory", address = {"PAL": 0x3E1B82, "NTSC": 0x3E0872}, connection_requirements = {"Entry from Spawn": [["Sky Flyer"], ["*Gear"], ["*Air Crawl"], ["*Expert"]], "Entry from Arena": [["Sky Flyer"], ["*Gear"], ["*Air Crawl"], ["*Expert"]], "Entry from Tunnel": [[]]}),
    Monkey(name = "Bob", level = "Vita-Z Factory", address = {"PAL": 0x3E1A68, "NTSC": 0x3E0758}, connection_requirements = {"Entry from Spawn": [["*Attack"], ["*Hard"]], "Entry from Arena": [["*Attack"], ["*Hard"]], "Entry from Tunnel": [["*Attack"], ["*Hard"]]}),
    Monkey(name = "Snap", level = "Vita-Z Factory", address = {"PAL": 0x3E1B81, "NTSC": 0x3E0871}, connection_requirements = {"Entry from Spawn": [["Sky Flyer"], ["*Gear"], ["*Air Crawl"], ["*Expert"]], "Entry from Arena": [[]], "Entry from Tunnel": [[]]}),
    Monkey(name = "Al", level = "Vita-Z Factory", address = {"PAL": 0x3E1B80, "NTSC": 0x3E0870}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Arena": [[]], "Entry from Tunnel": [[]]}),
    Monkey(name = "Chomp", level = "Vita-Z Factory", address = {"PAL": 0x3E1B83, "NTSC": 0x3E0873}, connection_requirements = {"Entry from Spawn": [["*Attack"], ["*Hard"]], "Entry from Arena": [["*Attack"], ["*Hard"]], "Entry from Tunnel": [["*Attack"], ["*Hard"]]}),
    Monkey(name = "Arnie", level = "Vita-Z Factory", address = {"PAL": 0x3E1B05, "NTSC": 0x3E07F5}, connection_requirements = {"Entry from Spawn": [["*Punch"]], "Entry from Arena": [["*Punch"]], "Entry from Tunnel": [["*Punch"]]}),
    Monkey(name = "Phil G.", level = "Vita-Z Factory", room = "Mech Tunnel", address = {"PAL": 0x3E1B93, "NTSC": 0x3E0883}, connection_requirements = {"Tunnel from Entry": [["*Radar"]], "Tunnel from Arena": [["*Radar"]]}),
    Monkey(name = "Bobby", level = "Vita-Z Factory", room = "Mech Arena", address = {"PAL": 0x3E1B84, "NTSC": 0x3E0874}, connection_requirements = {"Arena from Tunnel": [[]], "Arena from Entry": [[]]}),
    Monkey(name = "Skippy", level = "Vita-Z Factory", room = "Mech Arena", address = {"PAL": 0x3E1B85, "NTSC": 0x3E0875}, connection_requirements = {"Arena from Tunnel": [[]], "Arena from Entry": [[]]}),

    #Casino City 
    Monkey(name = "Pelvis", level = "Casino City", address = {"PAL": 0x3E1A94, "NTSC": 0x3E0784}, connection_requirements = {"Entry from Spawn": [["Catapult"]], "Entry from Bar": [["Catapult"]], "Entry from Circus": [["Catapult"]]}),
    Monkey(name = "Jessica", level = "Casino City", address = {"PAL": 0x3E1A93, "NTSC": 0x3E0783}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Bar": [[]], "Entry from Circus": [[]]}),
    Monkey(name = "Vincent", level = "Casino City", address = {"PAL": 0x3E1A95, "NTSC": 0x3E0785}, connection_requirements = {"Entry from Spawn": [["*Attack"], ["Catapult"], ["*Hard"]], "Entry from Bar": [[]], "Entry from Circus": [["*Attack"], ["Catapult"], ["*Hard"]]}),
    Monkey(name = "Shaft", level = "Casino City", address = {"PAL": 0x3E1A96, "NTSC": 0x3E0786}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Bar": [[]], "Entry from Circus": [[]]}),
    Monkey(name = "Jackson", level = "Casino City", address = {"PAL": 0x3E1A97, "NTSC": 0x3E0787}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Bar": [[]], "Entry from Circus": [[]]}),
    Monkey(name = "Oozy", level = "Casino City", address = {"PAL": 0x3E1A98, "NTSC": 0x3E0788}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Bar": [[]], "Entry from Circus": [[]]}),
    Monkey(name = "Simian Seagal", level = "Casino City", room = "Bar", address = {"PAL": 0x3E1A9A, "NTSC": 0x3E078A}, connection_requirements = {"Bar from Entry": [[]]}),
    Monkey(name = "Leo", level = "Casino City", room = "Bar", address = {"PAL": 0x3E1AA1, "NTSC": 0x3E0791}, connection_requirements = {"Bar from Entry": [["*Punch"]]}),
    Monkey(name = "Ulysses", level = "Casino City", room = "Bar", address = {"PAL": 0x3E1A9B, "NTSC": 0x3E078B}, connection_requirements = {"Bar from Entry": [[]]}),
    Monkey(name = "Clint Apewood", level = "Casino City", room = "Bar", address = {"PAL": 0x3E1A99, "NTSC": 0x3E0789}, connection_requirements = {"Bar from Entry": [[]]}),
    Monkey(name = "Raymond", level = "Casino City", room = "Circus", address = {"PAL": 0x3E1A9E, "NTSC": 0x3E078E}, connection_requirements = {"Circus from Entry": [["Catapult"], ["*Boost Fly", "*Expert"]]}),
    Monkey(name = "Vindy", level = "Casino City", room = "Circus", address = {"PAL": 0x3E1A9D, "NTSC": 0x3E078D}, connection_requirements = {"Circus from Entry": [[]]}),
    Monkey(name = "Pierrot", level = "Casino City", room = "Circus", address = {"PAL": 0x3E1A9F, "NTSC": 0x3E078F}, connection_requirements = {"Circus from Entry": [[]]}),
    Monkey(name = "Jester", level = "Casino City", room = "Circus", address = {"PAL": 0x3E1AA2, "NTSC": 0x3E0792}, connection_requirements = {"Circus from Entry": [["*Attack"], ["*Hard"]]}),
    Monkey(name = "Bubbles", level = "Casino City", room = "Circus", address = {"PAL": 0x3E1A9C, "NTSC": 0x3E078C}, connection_requirements = {"Circus from Entry": [[]]}),

    #Ninja Hideout
    Monkey(name = "Snooz", level = "Ninja Hideout", address = {"PAL": 0x3E1B39, "NTSC": 0x3E0829}, connection_requirements = {"Entry from Spawn": [["R.C. Car", "Water Net"], ["*Air Crawl"], ["R.C. Car", "*Hard"]], "Entry from Second Room": [["Water Net"], ["*Hard"]]}),
    Monkey(name = "Twiggy", level = "Ninja Hideout", address = {"PAL": 0x3E1AA3, "NTSC": 0x3E0793}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Second Room": [["R.C. Car"], ["*Air Crawl"]]}),
    Monkey(name = "Harry Karry", level = "Ninja Hideout", address = {"PAL": 0x3E1AA4, "NTSC": 0x3E0794}, connection_requirements = {"Entry from Spawn": [["R.C. Car"], ["*Air Crawl"]], "Entry from Second Room": [[]]}),
    Monkey(name = "Chan", level = "Ninja Hideout", address = {"PAL": 0x3E1AA7, "NTSC": 0x3E0797}, connection_requirements = {"Entry from Spawn": [["R.C. Car", "Water Net"], ["*Air Crawl"], ["R.C. Car", "*Expert", "*Boost Fly"]], "Entry from Second Room": [["Water Net"], ["*Air Crawl"], ["*Expert", "*Boost Fly"]]}),
    Monkey(name = "Duncan", level = "Ninja Hideout", address = {"PAL": 0x3E1AA6, "NTSC": 0x3E0796}, connection_requirements = {"Entry from Spawn": [["R.C. Car", "Water Net"], ["*Air Crawl"], ["R.C. Car", "Sky Flyer", "*Hard"], ["R.C. Car", "Pipotchi", "*Expert", "*Long Jump"]], "Entry from Second Room": [["R.C. Car", "Water Net"], ["*Air Crawl"], ["Sky Flyer", "*Hard"], ["Pipotchi", "*Expert", "*Long Jump"]]}),
    Monkey(name = "Somnia", level = "Ninja Hideout", address = {"PAL": 0x3E1AA5, "NTSC": 0x3E0795}, connection_requirements = {"Entry from Spawn": [["R.C. Car"]], "Entry from Second Room": [["R.C. Car"]]}),
    Monkey(name = "Hideyoshi", level = "Ninja Hideout", room = "Second Room", address = {"PAL": 0x3E1AAB, "NTSC": 0x3E079B}, connection_requirements = {"Second Room from Entry": [["*Attack"], ["*Hard"]], "Second Room from Third Room Start": [["*Attack"], ["*Hard"]], "Second Room from Third Room End": [["*Attack"], ["*Hard"]]}),
    Monkey(name = "Takashi", level = "Ninja Hideout", room = "Second Room", address = {"PAL": 0x3E1AAC, "NTSC": 0x3E079C}, connection_requirements = {"Second Room from Entry": [["*Attack"], ["*Hard"]], "Second Room from Third Room Start": [["*Attack"], ["*Hard"]], "Second Room from Third Room End": [["*Attack"], ["*Hard"]]}),
    Monkey(name = "Rapido", level = "Ninja Hideout", room = "Second Room", address = {"PAL": 0x3E1AA8, "NTSC": 0x3E0798}, connection_requirements = {"Second Room from Entry": [["*Attack"], ["*Hard"]], "Second Room from Third Room Start": [["*Attack"], ["*Hard"]], "Second Room from Third Room End": [["*Attack"], ["*Hard"]]}),
    Monkey(name = "Jim", level = "Ninja Hideout", room = "Second Room", address = {"PAL": 0x3E1AA9, "NTSC": 0x3E0799}, connection_requirements = {"Second Room from Entry": [["R.C. Car"]], "Second Room from Third Room Start": [["R.C. Car"]], "Second Room from Third Room End": [["R.C. Car"]]}),
    Monkey(name = "Bon-o", level = "Ninja Hideout", room = "Second Room", address = {"PAL": 0x3E1AAA, "NTSC": 0x3E079A}, connection_requirements = {"Second Room from Entry": [["*Attack"], ["*Hard"]], "Second Room from Third Room Start": [["*Attack"], ["*Hard"]], "Second Room from Third Room End": [["*Attack"], ["*Hard"]]}),
    Monkey(name = "Boxer", level = "Ninja Hideout", room = "Second Room", address = {"PAL": 0x3E1AEB, "NTSC": 0x3E07DB}, connection_requirements = {"Second Room from Entry": [["*Punch", "*Air Crawl"], ["*Punch", "R.C. Car"], ["*Punch", "Sky Flyer", "*Hard"], ["*Punch", "*Hard", "*Long Jump"]], "Second Room from Third Room Start": [["*Punch"]], "Second Room from Third Room End": [["*Punch", "*Air Crawl"], ["*Punch", "R.C. Car"], ["*Punch", "Sky Flyer", "*Hard"], ["*Punch", "Dash Hoop", "*Hard", "*Long Jump"]]}),
    Monkey(name = "Chuck", level = "Ninja Hideout", room = "Second Room", address = {"PAL": 0x3E1AAE, "NTSC": 0x3E079E}, connection_requirements = {"Second Room from Entry": [["*Attack", "*Air Crawl", "*Radar"], ["*Attack", "R.C. Car", "*Radar"], ["R.C. Car", "*Hard"], ["*Air Crawl", "*Hard"], ["Sky Flyer", "*Hard"], ["*Hard", "*Long Jump"]], "Second Room from Third Room Start": [["*Attack", "*Radar"], ["*Hard"]], "Second Room from Third Room End": [["*Attack", "*Air Crawl", "*Radar"], ["*Attack", "R.C. Car", "*Radar"], ["R.C. Car", "*Hard"], ["*Air Crawl", "*Hard"], ["Sky Flyer", "*Hard"], ["*Hard", "*Long Jump"]]}),
    Monkey(name = "Shiho", level = "Ninja Hideout", room = "Second Room", address = {"PAL": 0x3E1AAD, "NTSC": 0x3E079D}, connection_requirements = {"Second Room from Entry": [["*Air Crawl"], ["R.C. Car"], ["Sky Flyer", "*Hard"], ["*Hard", "*Long Jump"]], "Second Room from Third Room Start": [[]], "Second Room from Third Room End": [["*Air Crawl", "*Attack"], ["*Air Crawl", "*Hard"], ["R.C. Car", "*Attack"], ["R.C. Car", "*Hard"], ["Sky Flyer", "*Hard"], ["*Hard", "*Long Jump"]]}),
    Monkey(name = "Ledski", level = "Ninja Hideout", room = "Third Room", address = {"PAL": 0x3E1B0A, "NTSC": 0x3E07FA}, connection_requirements = {"Third Room Start from Second Room": [["*Gear"]], "Third Room End from Second Room": [["*Gear"]]}),
    Monkey(name = "Harvey", level = "Ninja Hideout", room = "Third Room", address = {"PAL": 0x3E1B09, "NTSC": 0x3E07F9}, connection_requirements = {"Third Room Start from Second Room": [["*Gear"]], "Third Room End from Second Room": [["*Gear"]]}),

    #Yellow Monkey Battle!
    Monkey(name = "Yellow Monkey", level = "Yellow Monkey Battle!", connection_requirements = {"Entry from Spawn": [["*Attack"], ["Catapult"], ["R.C. Car", "*Hard"], ["Bananarang", "*Hard"], ["Sky Flyer", "*Hard"], ["*Expert"]]}),

    #Snowball Mountain
    Monkey(name = "Bernie", level = "Snowball Mountain", address = {"PAL": 0x3E1AB2, "NTSC": 0x3E07A2}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Christmas Tree": [[]], "Entry from Ski Hill": [[]]}),
    Monkey(name = "Zebedee", level = "Snowball Mountain", address = {"PAL": 0x3E1AB1, "NTSC": 0x3E07A1}, connection_requirements = {"Entry from Spawn": [["*Air Crawl", "*Hard"], ["Sky Flyer", "*Hard"]], "Entry from Christmas Tree": [["*Air Crawl", "*Hard"], ["Sky Flyer", "*Hard"]], "Entry from Ski Hill": [[]]}),
    Monkey(name = "Jibber", level = "Snowball Mountain", address = {"PAL": 0x3E1AB0, "NTSC": 0x3E07A0}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Christmas Tree": [[]], "Entry from Ski Hill": [[]]}),
    Monkey(name = "Threedee", level = "Snowball Mountain", address = {"PAL": 0x3E1AEA, "NTSC": 0x3E07DA}, connection_requirements = {"Entry from Spawn": [["*Punch"]], "Entry from Christmas Tree": [["*Punch"]], "Entry from Ski Hill": [["*Punch"]]}),
    Monkey(name = "Monkey Claus", level = "Snowball Mountain", room = "Christmas Tree", address = {"PAL": 0x3E1AB6, "NTSC": 0x3E07A6}, connection_requirements = {"Christmas Tree from Entry": [["Sky Flyer", "*Hard"], ["Power Punch", "*Expert"], ["Catapult"]], "Christmas Tree from Ski Hill": [["Sky Flyer", "*Hard"], ["Power Punch", "*Expert"], ["Catapult"]]}),
    Monkey(name = "Chill ", level = "Snowball Mountain", room = "Christmas Tree", address = {"PAL": 0x3E1AB5, "NTSC": 0x3E07A5}, connection_requirements = {"Christmas Tree from Entry": [[]], "Christmas Tree from Ski Hill": [[]]}),
    Monkey(name = "Parka", level = "Snowball Mountain", room = "Christmas Tree", address = {"PAL": 0x3E1AB8, "NTSC": 0x3E07A8}, connection_requirements = {"Christmas Tree from Entry": [[]], "Christmas Tree from Ski Hill": [[]]}),
    Monkey(name = "Raver", level = "Snowball Mountain", room = "Christmas Tree", address = {"PAL": 0x3E1AB7, "NTSC": 0x3E07A7}, connection_requirements = {"Christmas Tree from Entry": [[]], "Christmas Tree from Ski Hill": [[]]}),
    Monkey(name = "Elodie", level = "Snowball Mountain", room = "Ski Hill", address = {"PAL": 0x3E1AD5, "NTSC": 0x3E07C5}, connection_requirements = {"Christmas Tree from Entry": [[]], "Christmas Tree from Ski Hill": [[]]}),
    Monkey(name = "Davee", level = "Snowball Mountain", room = "Ski Hill", address = {"PAL": 0x3E1A71, "NTSC": 0x3E0761}, connection_requirements = {"Ski Hill from Christmas Tree": [[]], "Ski Hill from Entry": [[]]}),
    Monkey(name = "Big Bopper", level = "Snowball Mountain", room = "Ski Hill", address = {"PAL": 0x3E1A6A, "NTSC": 0x3E075A}, connection_requirements = {"Ski Hill from Christmas Tree": [[]], "Ski Hill from Entry": [[]]}),
    Monkey(name = "Jimmy", level = "Snowball Mountain", room = "Ski Hill", address = {"PAL": 0x3E1AB4, "NTSC": 0x3E07A4}, connection_requirements = {"Ski Hill from Christmas Tree": [[]], "Ski Hill from Entry": [[]]}),
    Monkey(name = "Eddie the Falcon", level = "Snowball Mountain", room = "Ski Hill", address = {"PAL": 0x3E1AB3, "NTSC": 0x3E07A3}, connection_requirements = {"Ski Hill from Christmas Tree": [[]], "Ski Hill from Entry": [[]]}),
    Monkey(name = "Zippy", level = "Snowball Mountain", room = "Ski Hill", address = {"PAL": 0x3E1AAF, "NTSC": 0x3E079F}, connection_requirements = {"Ski Hill from Christmas Tree": [[]], "Ski Hill from Entry": [[]]}),

    #Lookout Valley
    Monkey(name = "Olivia", level = "Lookout Valley", address = {"PAL": 0x3E1ABB, "NTSC": 0x3E07AB}, connection_requirements = {"Entry from Spawn": [["*Valley Gap", "*Valley Island"]], "Entry from Jungle End": [[]], "Entry from Jungle Start": [[]], "Entry from Cave Start": [["Sky Flyer"], ["Water Net"], ["*Air Crawl"]], "Entry from Cave End": [["Sky Flyer"], ["Water Net"], ["*Air Crawl"]]}),
    Monkey(name = "Ally", level = "Lookout Valley", address = {"PAL": 0x3E1ABA, "NTSC": 0x3E07AA}, connection_requirements = {"Entry from Spawn": [["Catapult", "Sky Flyer", "Water Net"], ["*Air Crawl"]], "Entry from Jungle End": [["Water Net"], ["*Air Crawl"]], "Entry from Jungle Start": [["Water Net"], ["*Air Crawl"]], "Entry from Cave Start": [["Water Net"], ["*Air Crawl"]], "Entry from Cave End": [["Water Net"], ["*Air Crawl"]]}),
    Monkey(name = "Ty", level = "Lookout Valley", address = {"PAL": 0x3E1AB9, "NTSC": 0x3E07A9}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Jungle End": [["Water Net"], ["*Air Crawl"], ["Sky Flyer"]], "Entry from Jungle Start": [["Water Net"], ["*Air Crawl"], ["Sky Flyer"]], "Entry from Cave End": [["Water Net"], ["*Air Crawl"], ["Sky Flyer"]], "Entry from Cave Start": [["Water Net"], ["*Air Crawl"], ["*Boost Fly", "*Hard"]]}),
    Monkey(name = "Livingstone", level = "Lookout Valley", address = {"PAL": 0x3E1ABD, "NTSC": 0x3E07AD}, connection_requirements = {"Entry from Spawn": [["Catapult", "Sky Flyer", "Power Punch"], ["*Air Crawl", "Power Punch"]], "Entry from Jungle End": [["Power Punch"]], "Entry from Jungle Start": [["Power Punch"]], "Entry from Cave Start": [["Sky Flyer", "Power Punch"], ["Water Net", "Power Punch"], ["*Air Crawl", "Power Punch"]], "Entry from Cave End": [["Sky Flyer", "Power Punch"], ["Water Net", "Power Punch"], ["*Air Crawl", "Power Punch"]]}),
    Monkey(name = "Louis", level = "Lookout Valley", room = "Jungle", address = {"PAL": 0x3E1AC0, "NTSC": 0x3E07B0}, connection_requirements = {"Jungle Start from Entry": [[]], "Jungle End from Entry": [[]]}),
    Monkey(name = "Lily", level = "Lookout Valley", room = "Jungle", address = {"PAL": 0x3E1ABF, "NTSC": 0x3E07AF}, connection_requirements = {"Jungle Start from Entry": [[]], "Jungle End from Entry": [[]]}),
    Monkey(name = "Gunn", level = "Lookout Valley", room = "Jungle", address = {"PAL": 0x3E1ABE, "NTSC": 0x3E07AE}, connection_requirements = {"Jungle Start from Entry": [["Catapult"], ["Stun Club"], ["Power Punch"], ["*Hard", "Dash Hoop"], ["*Hard", "R.C. Car"], ["*Hard", "Sky Flyer"], ["*Hard", "Water Cannon"], ["*Expert", "*Damage Boost"]], "Jungle End from Entry": [["Catapult"], ["Stun Club"], ["Power Punch"], ["*Hard", "Dash Hoop"], ["*Hard", "R.C. Car"], ["*Hard", "Sky Flyer"], ["*Hard", "Water Cannon"], ["*Expert", "*Damage Boost"]]}),
    Monkey(name = "Gill", level = "Lookout Valley", room = "Cave", address = {"PAL": 0x3E1AC3, "NTSC": 0x3E07B3}, connection_requirements = {"Cave End from Entry": [["Water Net", "Catapult"], ["*Hard"]], "Cave Start from Entry": [["*Valley Button", "*Valley Stalag", "Catapult", "Water Net"], ["*Valley Button", "*Valley Stalag", "*Hard"]]}),
    Monkey(name = "Chris", level = "Lookout Valley", room = "Cave", address = {"PAL": 0x3E1AC2, "NTSC": 0x3E07B2}, connection_requirements = {"Cave End from Entry": [[]], "Cave Start from Entry": [["*Valley Button", "*Valley Stalag", "Water Net"], ["*Valley Button", "*Valley Stalag", "Sky Flyer", "*Hard"], ["*Valley Button", "*Valley Stalag", "*Expert"]]}),
    Monkey(name = "Simian Tell", level = "Lookout Valley", room = "Cave", address = {"PAL": 0x3E1AC1, "NTSC": 0x3E07B1}, connection_requirements = {"Cave End from Entry": [["*Air Crawl"], ["R.C. Car", "Water Net"], ["*Boost Fly", "*Hard"], ["R.C. Car", "*Hard"]], "Cave Start from Entry": [["*Air Crawl"], ["*Valley Button", "*Valley Stalag", "R.C. Car"], ["*Valley Button", "*Valley Stalag", "*Boost Fly", "*Hard"]]}),

    #The Blue Baboon
    Monkey(name = "Helmut", level = "The Blue Baboon", address = {"PAL": 0x3E1AC7, "NTSC": 0x3E07B7}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Bananarang Room": [[]], "Entry from Ship": [[]], "Entry from Changing Hut": [[]]}),
    Monkey(name = "Sandy", level = "The Blue Baboon", address = {"PAL": 0x3E1AC5, "NTSC": 0x3E07B5}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Bananarang Room": [[]], "Entry from Ship": [[]], "Entry from Changing Hut": [[]]}),
    Monkey(name = "Gloria", level = "The Blue Baboon", address = {"PAL": 0x3E1AC4, "NTSC": 0x3E07B4}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Bananarang Room": [[]], "Entry from Ship": [[]], "Entry from Changing Hut": [[]]}),
    Monkey(name = "Michelle", level = "The Blue Baboon", address = {"PAL": 0x3E1AC9, "NTSC": 0x3E07B9}, connection_requirements = {"Entry from Spawn": [["Bananarang"], ["*Hard"]], "Entry from Bananarang Room": [["Bananarang", "Water Net"], ["*Air Crawl", "Bananarang"], ["*Air Crawl", "*Hard"], ["Water Net", "*Hard"]], "Entry from Ship": [["Bananarang"], ["*Hard"]], "Entry from Changing Hut": [["Bananarang"], ["*Hard"]]}),
    Monkey(name = "Erin", level = "The Blue Baboon", address = {"PAL": 0x3E1ACA, "NTSC": 0x3E07BA}, connection_requirements = {"Entry from Spawn": [["*Punch"]], "Entry from Bananarang Room": [["*Punch", "Water Net"], ["*Punch", "*Air Crawl"]], "Entry from Ship": [["*Punch"]], "Entry from Changing Hut": [["*Punch"]]}),
    Monkey(name = "Brad", level = "The Blue Baboon", address = {"PAL": 0x3E1AC6, "NTSC": 0x3E07B6}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Bananarang Room": [[]], "Entry from Ship": [[]], "Entry from Changing Hut": [[]]}),
    Monkey(name = "Mulder", level = "The Blue Baboon", room = "Bananarang Room", address = {"PAL": 0x3E1B86, "NTSC": 0x3E0876}, connection_requirements = {"Bananarang Room from Entry": [["*UFO"]]}),
    Monkey(name = "Rik", level = "The Blue Baboon", room = "Bananarang Room", address = {"PAL": 0x3E1B87, "NTSC": 0x3E0877}, connection_requirements = {"Bananarang Room from Entry": [["Bananarang", "Water Net"]]}),
    Monkey(name = "Montague", level = "The Blue Baboon", room = "Ship", address = {"PAL": 0x3E1ACB, "NTSC": 0x3E07BB}, connection_requirements = {"Ship from Entry": [["Water Net"], ["*Hard"]]}),
    Monkey(name = "Shorty", level = "The Blue Baboon", room = "Ship", address = {"PAL": 0x3E1ACD, "NTSC": 0x3E07BD}, connection_requirements = {"Ship from Entry": [["Bananarang"]]}),
    Monkey(name = "Speedo", level = "The Blue Baboon", room = "Ship", address = {"PAL": 0x3E1ACC, "NTSC": 0x3E07BC}, connection_requirements = {"Ship from Entry": [["Water Net"], ["*Hard"]]}),
    Monkey(name = "Sooz", level = "The Blue Baboon", room = "Changing Hut", address = {"PAL": 0x3E1B3A, "NTSC": 0x3E082A}, connection_requirements = {"Changing Hut from Entry": [[]]}),

    #Pink Monkey Battle!
    Monkey(name = "Pink Monkey", level = "Pink Monkey Battle!", address = {"PAL": 0x3E1BAA, "NTSC": 0x3E089A}, connection_requirements = {"Entry from Spawn": [["Sky Flyer", "Water Net", "*Attack"], ["Water Net", "*Attack", "*Hard"], ["Water Net", "R.C. Car", "*Hard"], ["Water Net", "Catapult", "*Hard"], ["Water Net", "Bananarang", "*Hard"]]}),

    #Enter the Monkey
    Monkey(name = "Jean Paul", level = "Enter the Monkey", address = {"PAL": 0x3E1ACF, "NTSC": 0x3E07BF}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Wall Start": [[]], "Entry from Inside Start": [[]], "Entry from Inside End": [[]], "Entry from Wall End": [["*Gear"]]}),
    Monkey(name = "Simeski", level = "Enter the Monkey", address = {"PAL": 0x3E1ACE, "NTSC": 0x3E07BE}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Wall Start": [[]], "Entry from Inside Start": [[]], "Entry from Inside End": [[]], "Entry from Wall End": [["*Gear"]]}),
    Monkey(name = "Barry", level = "Enter the Monkey", address = {"PAL": 0x3E1AD1, "NTSC": 0x3E07C1}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Wall Start": [[]], "Entry from Inside Start": [[]], "Entry from Inside End": [[]], "Entry from Wall End": [["*Gear"]]}),
    Monkey(name = "Chan ", level = "Enter the Monkey", address = {"PAL": 0x3E1AD0, "NTSC": 0x3E07C0}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Wall Start": [[]], "Entry from Inside Start": [[]], "Entry from Inside End": [[]], "Entry from Wall End": [["*Gear"]]}),
    Monkey(name = "Marshall", level = "Enter the Monkey", address = {"PAL": 0x3E1AD3, "NTSC": 0x3E07C3}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Wall Start": [[]], "Entry from Inside Start": [[]], "Entry from Inside End": [[]], "Entry from Wall End": [["*Gear"]]}),
    Monkey(name = "Wesley", level = "Enter the Monkey", address = {"PAL": 0x3E1AD2, "NTSC": 0x3E07C2}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Wall Start": [[]], "Entry from Inside Start": [[]], "Entry from Inside End": [[]], "Entry from Wall End": [["*Gear"]]}),
    Monkey(name = "Chaz", level = "Enter the Monkey", address = {"PAL": 0x3E1AD4, "NTSC": 0x3E07C4}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Wall Start": [[]], "Entry from Inside Start": [[]], "Entry from Inside End": [[]], "Entry from Wall End": [["*Gear"]]}),
    Monkey(name = "Daimion", level = "Enter the Monkey", address = {"PAL": 0x3E1AD8, "NTSC": 0x3E07C8}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Wall Start": [[]], "Entry from Inside Start": [[]], "Entry from Inside End": [[]], "Entry from Wall End": [["*Gear"]]}),
    Monkey(name = "Bruce Monkee", room = "Inside", level = "Enter the Monkey", address = {"PAL": 0x3E1ADE, "NTSC": 0x3E07CE}, connection_requirements = {"Inside Start from Entry": [["*Punch", "*Gear"]], "Inside End from Entry": [["*Punch", "Water Net"], ["*Punch", "*Air Crawl"]]}),
    Monkey(name = "Miyazaki", room = "Inside", level = "Enter the Monkey", address = {"PAL": 0x3E1ADD, "NTSC": 0x3E07CD}, connection_requirements = {"Inside Start from Entry": [["*Gear", "*Attack"], ["*Gear", "*Hard"]], "Inside End from Entry": [["Water Net", "*Attack"], ["*Air Crawl", "*Attack"], ["Water Net", "*Hard"], ["*Air Crawl", "*Hard"]]}),
    Monkey(name = "Johnny", room = "Inside", level = "Enter the Monkey", address = {"PAL": 0x3E1ADF, "NTSC": 0x3E07CF}, connection_requirements = {"Inside Start from Entry": [["*Gear", "*Radar", "Water Net", "*Attack"], ["*Gear", "*Hard"]], "Inside End from Entry": [["Water Net", "*Radar", "*Attack"], ["*Air Crawl", "*Radar", "*Attack"], ["*Air Crawl", "*Hard"], ["Water Net", "*Hard"]]}),
    Monkey(name = "Naseem", room = "Inside", level = "Enter the Monkey", address = {"PAL": 0x3E1AE0, "NTSC": 0x3E07D0}, connection_requirements = {"Inside Start from Entry": [["*Attack"], ["*Hard"]]}),
    Monkey(name = "Ming", room = "Wall", level = "Enter the Monkey", address = {"PAL": 0x3E1AE9, "NTSC": 0x3E07D9}, connection_requirements = {"Wall Start from Entry": [["R.C. Car"], ["*Air Crawl"], ["*Boost Fly", "*Hard"]], "Wall End from Entry": [[]]}),
    Monkey(name = "Ryan", room = "Wall", level = "Enter the Monkey", address = {"PAL": 0x3E1AE4, "NTSC": 0x3E07D4}, connection_requirements = {"Wall Start from Entry": [["Sky Flyer"], ["Catapult"], ["*Hard"]], "Wall End from Entry": [["Sky Flyer"], ["Catapult"], ["*Hard"]]}),
    Monkey(name = "Martin", room = "Wall", level = "Enter the Monkey", address = {"PAL": 0x3E1AE3, "NTSC": 0x3E07D3}, connection_requirements = {"Wall Start from Entry": [[]], "Wall End from Entry": [[]]}),
    Monkey(name = "Jools", room = "Wall", level = "Enter the Monkey", address = {"PAL": 0x3E1AE8, "NTSC": 0x3E07D8}, connection_requirements = {"Wall Start from Entry": [[]], "Wall End from Entry": [[]]}),
    Monkey(name = "James", room = "Wall", level = "Enter the Monkey", address = {"PAL": 0x3E1AE6, "NTSC": 0x3E07D6}, connection_requirements = {"Wall Start from Entry": [[]], "Wall End from Entry": [[]]}),
    Monkey(name = "John Ook", room = "Wall", level = "Enter the Monkey", address = {"PAL": 0x3E1AE7, "NTSC": 0x3E07D7}, connection_requirements = {"Wall Start from Entry": [[]], "Wall End from Entry": [[]]}),
    Monkey(name = "Goku", room = "Wall", level = "Enter the Monkey", address = {"PAL": 0x3E1AD7, "NTSC": 0x3E07C7}, connection_requirements = {"Wall Start from Entry": [["Catapult", "R.C. Car"], ["*Air Crawl"], ["*Boost Fly", "*Hard", "Catapult"], ["*Boost Fly", "*Expert"]], "Wall End from Entry": [["Catapult"], ["*Boost Fly", "*Expert"]]}),
    Monkey(name = "Daniel C. Ooke", room = "Wall", level = "Enter the Monkey", address = {"PAL": 0x3E1AEC, "NTSC": 0x3E07DC}, connection_requirements = {"Wall Start from Entry": [[]], "Wall End from Entry": [[]]}),

    #Simian Citadel
    Monkey(name = "Sly", level = "Simian Citadel", address = {"PAL": 0x3E1AFA, "NTSC": 0x3E07EA}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Bullring": [["*Gear"]], "Entry from Fountain": [[]]}),
    Monkey(name = "Norman", level = "Simian Citadel", address = {"PAL": 0x3E1AFC, "NTSC": 0x3E07EC}, connection_requirements = {"Entry from Spawn": [["*Gear", "Water Net"]], "Entry from Bullring": [[]], "Entry from Fountain": [["*Gear", "Water Net"]]}),
    Monkey(name = "Alex", level = "Simian Citadel", address = {"PAL": 0x3E1AF9, "NTSC": 0x3E07E9}, connection_requirements = {"Entry from Spawn": [["Bananarang"]], "Entry from Bullring": [["*Gear", "Water Net", "Bananarang"]], "Entry from Fountain": [["Bananarang"]]}),
    Monkey(name = "Jonah", level = "Simian Citadel", room = "Whale", address = {"PAL": 0x3E1B88, "NTSC": 0x3E0878}, connection_requirements = {"Whale from Bullring": [["Sky Flyer", "Water Net", "*Attack"], ["Sky Flyer", "*Hard"], ["*Air Crawl"]]}),
    Monkey(name = "Mermonkey", level = "Simian Citadel", room = "Whale", address = {"PAL": 0x3E1B89, "NTSC": 0x3E0879}, connection_requirements = {"Whale from Bullring": [["Water Net", "Sky Flyer"], ["Water Net", "*Air Crawl"]]}),
    Monkey(name = "Colin", level = "Simian Citadel", room = "Whale", address = {"PAL": 0x3E1B8A, "NTSC": 0x3E087A}, connection_requirements = {"Whale from Bullring": [["Sky Flyer", "Water Net", "*Attack"], ["Sky Flyer", "*Hard"], ["*Air Crawl"]]}),
    Monkey(name = "Nicky", level = "Simian Citadel", room = "Submarine", address = {"PAL": 0x3E1B37, "NTSC": 0x3E0827}, connection_requirements = {"Submarine from Whale": [[]], "Submarine from Fountain": [[]]}),
    Monkey(name = "Vaughan", level = "Simian Citadel", room = "Submarine", address = {"PAL": 0x3E1B36, "NTSC": 0x3E0826}, connection_requirements = {"Submarine from Whale": [[]], "Submarine from Fountain": [[]]}),
    Monkey(name = "Dave", level = "Simian Citadel", room = "Fountain", address = {"PAL": 0x3E1B04, "NTSC": 0x3E07F4}, connection_requirements = {"Fountain from Entry": [[]], "Fountain from Submarine": [[]]}),
    Monkey(name = "Gonzales", level = "Simian Citadel", room = "Fountain", address = {"PAL": 0x3E1B06, "NTSC": 0x3E07F6}, connection_requirements = {"Fountain from Entry": [["*Attack"], ["*Hard"]], "Fountain from Submarine": [["*Attack"], ["*Hard"]]}),
    Monkey(name = "Daley", level = "Simian Citadel", room = "Fountain", address = {"PAL": 0x3E1B07, "NTSC": 0x3E07F7}, connection_requirements = {"Fountain from Entry": [["*Attack"], ["Catapult"]], "Fountain from Submarine": [["*Attack"], ["Catapult"]]}),
    Monkey(name = "Ollie", level = "Simian Citadel", room = "Fountain", address = {"PAL": 0x3E1B02, "NTSC": 0x3E07F2}, connection_requirements = {"Fountain from Entry": [[]], "Fountain from Submarine": [[]]}),
    Monkey(name = "Dolph", level = "Simian Citadel", room = "Fountain", address = {"PAL": 0x3E1B08, "NTSC": 0x3E07F8}, connection_requirements = {"Fountain from Entry": [["*Punch"]], "Fountain from Submarine": [["*Punch"]]}),
    Monkey(name = "Tommy", level = "Simian Citadel", room = "Fountain", address = {"PAL": 0x3E1B01, "NTSC": 0x3E07F1}, connection_requirements = {"Fountain from Entry": [["*Attack"], ["*Hard"]], "Fountain from Submarine": [["*Attack"], ["*Hard"]]}),
    Monkey(name = "Grace", level = "Simian Citadel", room = "Fountain", address = {"PAL": 0x3E1B03, "NTSC": 0x3E07F3}, connection_requirements = {"Fountain from Entry": [["Sky Flyer"], ["Catapult"], ["Stun Club", "*Boost Jump", "*Hard"]], "Fountain from Submarine": [["Sky Flyer"], ["Catapult"], ["Stun Club", "*Boost Jump", "*Hard"]]}),
    Monkey(name = "Jim ", level = "Simian Citadel", room = "Bullring", address = {"PAL": 0x3E1AFF, "NTSC": 0x3E07EF}, connection_requirements = {"Bullring from Entry": [["*Bull Fight", "Dash Hoop"], ["*Bull Fight", "*Hard"]], "Bullring from Whale": [["*Bull Fight"]]}),
    Monkey(name = "Rex", level = "Simian Citadel", room = "Bullring", address = {"PAL": 0x3E1B00, "NTSC": 0x3E07F0}, connection_requirements = {"Bullring from Entry": [["*Bull Fight", "Dash Hoop"], ["*Bull Fight", "*Hard"]], "Bullring from Whale": [[]]}),
    Monkey(name = "Brucie", level = "Simian Citadel", room = "Bullring", address = {"PAL": 0x3E1AFE, "NTSC": 0x3E07EE}, connection_requirements = {"Bullring from Entry": [["*Bull Fight", "Dash Hoop"], ["*Bull Fight", "*Hard"]], "Bullring from Whale": [[]]}),
    Monkey(name = "Woody", level = "Simian Citadel", room = "Bullring", address = {"PAL": 0x3E1AFD, "NTSC": 0x3E07ED}, connection_requirements = {"Bullring from Entry": [["*Bull Fight", "Dash Hoop"], ["*Bull Fight", "*Hard"]], "Bullring from Whale": [[]]}),

    #Panic Pyramid
    Monkey(name = "Piz", level = "Panic Pyramid", address = {"PAL": 0x3E1AED, "NTSC": 0x3E07DD}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Moving Platforms #2": [[]], "Entry from Boulders Start": [[]], "Entry from Boulders End": [[]], "Entry from Booby Traps": [[]]}), 
    Monkey(name = "Stu", level = "Panic Pyramid", address = {"PAL": 0x3E1AEE, "NTSC": 0x3E07DE}, connection_requirements = {"Entry from Spawn": [["*Air Crawl"], ["Sky Flyer"]], "Entry from Moving Platforms #2": [["*Air Crawl"], ["Sky Flyer"]], "Entry from Boulders Start": [["*Air Crawl"], ["Sky Flyer"]], "Entry from Boulders End": [["*Air Crawl"], ["Sky Flyer"]], "Entry from Booby Traps": [["*Air Crawl"], ["Sky Flyer"]]}),
    Monkey(name = "Stevie", room = "Booby Traps", level = "Panic Pyramid", address = {"PAL": 0x3E1AF1, "NTSC": 0x3E07E1}, connection_requirements = {"Booby Traps from Entry": [["*Pyramid Sarcophagus", "Water Net"]], "Booby Traps from Moving Platforms #1": [["Water Net", "*Gear", "R.C. Car"]]}),
    Monkey(name = "Jimbo", room = "Booby Traps", level = "Panic Pyramid", address = {"PAL": 0x3E1AEF, "NTSC": 0x3E07DF}, connection_requirements = {"Booby Traps from Entry": [[]], "Booby Traps from Moving Platforms #1": [["*Gear"]]}),
    Monkey(name = "Roberts", room = "Booby Traps", level = "Panic Pyramid", address = {"PAL": 0x3E1AF0, "NTSC": 0x3E07E0}, connection_requirements = {"Booby Traps from Entry": [["*Pyramid Sarcophagus"]], "Booby Traps from Moving Platforms #1": [["*Gear"]]}),
    Monkey(name = "Uri", level = "Panic Pyramid", room = "Moving Platforms #1", address = {"PAL": 0x3E1AF4, "NTSC": 0x3E07E4}, connection_requirements = {"Moving Platforms #1 from Booby Traps": [["Water Cannon"], ["*Air Crawl", "*Hard"], ["*Expert"]], "Moving Platforms #1 from Moving Platforms #2": [["Water Cannon"], ["*Air Crawl", "*Hard"], ["*Expert"]]}),
    Monkey(name = "Eric", level = "Panic Pyramid", room = "Moving Platforms #1", address = {"PAL": 0x3E1AF3, "NTSC": 0x3E07E3}, connection_requirements = {"Moving Platforms #1 from Booby Traps": [[]], "Moving Platforms #1 from Moving Platforms #2": [["Water Cannon"], ["*Air Crawl"], ["R.C. Car"]]}),
    Monkey(name = "Curley", level = "Panic Pyramid", room = "Boulders", address = {"PAL": 0x3E1B30, "NTSC": 0x3E0820}, connection_requirements = {"Boulders Start from Entry": [["R.C. Car"], ["*Air Crawl"]], "Boulders End from Entry": [[]]}),
    Monkey(name = "Chimpette", level = "Panic Pyramid", room = "Boulders", address = {"PAL": 0x3E1B34, "NTSC": 0x3E0824}, connection_requirements = {"Boulders Start from Entry": [["R.C. Car"], ["*Air Crawl"]], "Boulders End from Entry": [[]]}),
    Monkey(name = "Dane", level = "Panic Pyramid", room = "Boulders", address = {"PAL": 0x3E1B33, "NTSC": 0x3E0823}, connection_requirements = {"Boulders Start from Entry": [["R.C. Car", "Catapult"], ["*Air Crawl"], ["*Hard", "*Boost Fly", "*Long Jump"]], "Boulders End from Entry": [["Catapult"]]}),
    Monkey(name = "Slim", level = "Panic Pyramid", room = "Boulders", address = {"PAL": 0x3E1B32, "NTSC": 0x3E0822}, connection_requirements = {"Boulders Start from Entry": [["R.C. Car"], ["*Air Crawl"]], "Boulders End from Entry": [[]]}),
    Monkey(name = "Cleo", level = "Panic Pyramid", address = {"PAL": 0x3E1AF2, "NTSC": 0x3E07E2}, room = "Boulders", connection_requirements = {"Boulders Start from Entry": [["R.C. Car", "*Punch"], ["*Air Crawl", "*Punch"]], "Boulders End from Entry": [["*Punch"]]}),
    Monkey(name = "Spud", level = "Panic Pyramid", address = {"PAL": 0x3E1AF7, "NTSC": 0x3E07E7}, room = "Moving Platforms #2", connection_requirements = {"Moving Platforms #2 from Moving Platforms #1": [["Water Cannon", "Dash Hoop"], ["*Damage Boost", "Dash Hoop"], ["Water Cannon", "*Air Crawl"], ["*Damage Boost", "*Air Crawl"]], "Moving Platforms #2 from Entry": [["Water Cannon"], ["*Damage Boost"]]}),
    Monkey(name = "Anthony", level = "Panic Pyramid", room = "Moving Platforms #2", address = {"PAL": 0x3E1B31, "NTSC": 0x3E0821}, connection_requirements = {"Moving Platforms #2 from Moving Platforms #1": [["*Punch", "Water Cannon", "Dash Hoop"], ["*Punch", "*Damage Boost", "Dash Hoop"], ["*Punch", "Water Cannon", "*Air Crawl"], ["*Punch", "*Damage Boost", "*Air Crawl"]], "Moving Platforms #2 from Entry": [["*Punch", "Water Cannon"], ["*Punch", "*Damage Boost"]]}),
    Monkey(name = "Becky", level = "Panic Pyramid", room = "Moving Platforms #2", address = {"PAL": 0x3E1AF5, "NTSC": 0x3E07E5}, connection_requirements = {"Moving Platforms #2 from Moving Platforms #1": [[]], "Moving Platforms #2 from Entry": [["Dash Hoop"], ["*Air Crawl"]]}),
    Monkey(name = "Gordon", level = "Panic Pyramid", room = "Moving Platforms #2", address = {"PAL": 0x3E1AF6, "NTSC": 0x3E07E6}, connection_requirements = {"Moving Platforms #2 from Moving Platforms #1": [[]], "Moving Platforms #2 from Entry": [["Dash Hoop"], ["*Air Crawl"]]}),
    Monkey(name = "Sphinx", level = "Panic Pyramid", room = "Moving Platforms #2", address = {"PAL": 0x3E1AF8, "NTSC": 0x3E07E8}, connection_requirements = {"Moving Platforms #2 from Entry": [["*Radar", "*Attack"], ["*Hard"]], "Moving Platforms #2 from Moving Platforms #1": [["Dash Hoop", "*Radar", "*Attack"], ["*Air Crawl", "*Radar", "*Attack"], ["*Air Crawl", "*Hard"], ["Dash Hoop", "*Hard"]]}),

    #White Monkey Battle!
    Monkey(name = "White Monkey", level = "White Monkey Battle!", address = {"PAL": 0x3E1BAB, "NTSC": 0x3E089B}, connection_requirements = {"Entry from Spawn": [["*Attack"], ["Catapult", "*Hard"], ["R.C. Car", "*Hard"], ["Bananarang", "*Expert"]]}),

    #Pirate Isle
    Monkey(name = "Pugwash", level = "Pirate Isle", address = {"PAL": 0x3E1B56, "NTSC": 0x3E0846}, connection_requirements = {"Entry from Spawn": [["Water Net"], ["*Hard"]], "Entry from Cave Entrance": [["Water Net"], ["*Hard"]], "Entry from Mine": [["Water Net"], ["*Hard"]]}),
    Monkey(name = "Burt", level = "Pirate Isle", address = {"PAL": 0x3E1B57, "NTSC": 0x3E0847}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Cave Entrance": [[]], "Entry from Mine": [[]]}),
    Monkey(name = "Hawkins", level = "Pirate Isle", address = {"PAL": 0x3E1B55, "NTSC": 0x3E0845}, connection_requirements = {"Entry from Spawn": [["Water Net"], ["*Hard"]], "Entry from Cave Entrance": [["Water Net"], ["*Hard"]], "Entry from Mine": [["Water Net"], ["*Hard"]]}),
    Monkey(name = "Kelly", level = "Pirate Isle", address = {"PAL": 0x3E1B58, "NTSC": 0x3E0848}, connection_requirements = {"Entry from Spawn": [["Sky Flyer", "Water Net"], ["*Air Crawl", "Water Net"], ["*Air Crawl", "*Expert"], ["*Boost Jump", "*Expert", "Water Net"]], "Entry from Mine": [["Sky Flyer", "Water Net"], ["*Air Crawl", "Water Net"], ["*Boost Jump", "*Expert", "Water Net"], ["*Air Crawl", "*Expert"]], "Entry from Cave Entrance": [["Sky Flyer", "Water Net"], ["*Air Crawl", "Water Net"], ["*Boost Jump", "*Expert", "Water Net"], ["*Air Crawl", "*Expert"]]}),
    Monkey(name = "Stephenson", level = "Pirate Isle", address = {"PAL": 0x3E1B59, "NTSC": 0x3E0849}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Cave Entrance": [[]], "Entry from Mine": [[]]}),
    Monkey(name = "Mel", level = "Pirate Isle", room = "Cave Entrance", address = {"PAL": 0x3E1B74, "NTSC": 0x3E0864}, connection_requirements = {"Cave Entrance from Entry": [["Water Cannon"], ["*Hard", "*Damage Boost"]], "Cave Entrance from Boat": [["Water Cannon"], ["*Hard", "*Damage Boost"]]}),
    Monkey(name = "Dick", level = "Pirate Isle", room = "Cave Entrance", address = {"PAL": 0x3E1B54, "NTSC": 0x3E0844}, connection_requirements = {"Cave Entrance from Entry": [["Water Cannon"], ["*Air Crawl"], ["Stun Club", "*Expert"], ["Sky Flyer", "*Boost Fly", "*Hard"]], "Cave Entrance from Boat": [[]]}),
    Monkey(name = "Bradley", level = "Pirate Isle", room = "Cave Entrance", address = {"PAL": 0x3E1B5B, "NTSC": 0x3E084B}, connection_requirements = {"Cave Entrance from Entry": [["Water Cannon"], ["*Expert", "*Damage Boost"]], "Cave Entrance from Boat": [["Water Cannon"], ["*Expert", "*Damage Boost"]]}),
    Monkey(name = "Tabasco", level = "Pirate Isle", room = "Boat", address = {"PAL": 0x3E1B5E, "NTSC": 0x3E084E}, connection_requirements = {"Boat from Cave Entrance": [[]], "Boat from Mine": [["Water Cannon"], ["*Air Crawl"]], "Boat from Cell": [[]], "Boat from Treasure": [[]]}),
    Monkey(name = "Bonzo", level = "Pirate Isle", room = "Boat", address = {"PAL": 0x3E1B5D, "NTSC": 0x3E084D}, connection_requirements = {"Boat from Cave Entrance": [[]], "Boat from Mine": [["Water Cannon"], ["*Air Crawl"]], "Boat from Cell": [[]], "Boat from Treasure": [[]]}),
    Monkey(name = "Scratchy", level = "Pirate Isle", address = {"PAL": 0x3E1B5A, "NTSC": 0x3E084A}, room = "Mine", connection_requirements = {"Mine from Boat": [[]], "Mine from Entry": [[]]}),
    Monkey(name = "Vic ", level = "Pirate Isle", room = "Mine", address = {"PAL": 0x3E1B78, "NTSC": 0x3E0868}, connection_requirements = {"Mine from Boat": [["*Attack"], ["*Hard"]], "Mine from Entry": [["*Attack"], ["*Hard"]]}),
    Monkey(name = "Indy", level = "Pirate Isle", room = "Mine", address = {"PAL": 0x3E1B7A, "NTSC": 0x3E086A}, connection_requirements = {"Mine from Boat": [["*Attack"], ["*Hard"]], "Mine from Entry": [["*Attack"], ["*Hard"]]}),
    Monkey(name = "Bobby ", level = "Pirate Isle", room = "Mine", address = {"PAL": 0x3E1B79, "NTSC": 0x3E0869}, connection_requirements = {"Mine from Boat": [[]], "Mine from Entry": [[]]}),
    Monkey(name = "Freddie", level = "Pirate Isle", room = "Dungeon", address = {"PAL": 0x3E1B60, "NTSC": 0x3E0850}, connection_requirements = {"Treasure from Boat": [["Stun Club"], ["Power Punch"], ["Catapult"], ["*Hard"]]}),
    Monkey(name = "Denis", level = "Pirate Isle", room = "Dungeon", address = {"PAL": 0x3E1B62, "NTSC": 0x3E0852}, connection_requirements = {"Treasure from Boat": [["Dash Hoop", "R.C. Car", "*Radar", "Stun Club"], ["Dash Hoop", "R.C. Car", "Moneky Radar", "Power Punch"], ["R.C. Car", "*Hard"]]}),
    Monkey(name = "Oliver", level = "Pirate Isle", room = "Dungeon", address = {"PAL": 0x3E1B5F, "NTSC": 0x3E084F}, connection_requirements = {"Treasure from Boat": [["Stun Club"], ["Power Punch"], ["Catapult"], ["*Hard"]]}),
    Monkey(name = "Captain Ook", level = "Pirate Isle", room = "Dungeon", address = {"PAL": 0x3E1B5C, "NTSC": 0x3E084C}, connection_requirements = {"Treasure from Boat": [["Stun Club"], ["Power Punch"], ["Catapult"], ["*Hard"]]}),
    Monkey(name = "Jeffrey", level = "Pirate Isle", room = "Dungeon", address = {"PAL": 0x3E1B61, "NTSC": 0x3E0851}, connection_requirements = {"Cell from Boat": [[]]}),
    Monkey(name = "Lee", level = "Pirate Isle", room = "Dungeon", address = {"PAL": 0x3E1B73, "NTSC": 0x3E0863}, connection_requirements = {"Treasure from Boat": [["*Punch", "R.C. Car", "Dash Hoop"], ["R.C. Car", "Power Punch", "*Hard"]]}),

    #Land of the Apes
    Monkey(name = "Rupert", level = "Land of the Apes", room = "Spa", address = {"PAL": 0x3E1B67, "NTSC": 0x3E0857}, connection_requirements = {"Spa from Icicles": [["*Punch"]]}),
    Monkey(name = "Craig", level = "Land of the Apes", room = "Spa", address = {"PAL": 0x3E1B50, "NTSC": 0x3E0840}, connection_requirements = {"Spa from Icicles": [[]]}),
    Monkey(name = "Hear No Evil", level = "Land of the Apes", room = "Spa", address = {"PAL": 0x3E1B4E, "NTSC": 0x3E083E}, connection_requirements = {"Spa from Icicles": [["*Attack"], ["*Hard"]]}),
    Monkey(name = "Brian", level = "Land of the Apes", room = "Spa", address = {"PAL": 0x3E1B4F, "NTSC": 0x3E083F}, connection_requirements = {"Spa from Icicles": [[]]}),
    Monkey(name = "Smell No Evil", level = "Land of the Apes", room = "Spa", address = {"PAL": 0x3E1B4C, "NTSC": 0x3E083C}, connection_requirements = {"Spa from Icicles": [[]]}),
    Monkey(name = "Speak No Evil", level = "Land of the Apes", room = "Spa", address = {"PAL": 0x3E1B4D, "NTSC": 0x3E083D}, connection_requirements = {"Spa from Icicles": [[]]}),
    Monkey(name = "Bones", level = "Land of the Apes", room = "Spa", address = {"PAL": 0x3E1B52, "NTSC": 0x3E0842}, connection_requirements = {"Spa from Icicles": [[]]}),
    Monkey(name = "Mr Frosty", level = "Land of the Apes", room = "Spa", address = {"PAL": 0x3E1B53, "NTSC": 0x3E0843}, connection_requirements = {"Spa from Icicles": [["Sky Flyer"], ["*Hard"]]}),
    Monkey(name = "Lynn", level = "Land of the Apes", room = "Spa", address = {"PAL": 0x3E1B51, "NTSC": 0x3E0841}, connection_requirements = {"Spa from Icicles": [[]]}),
    Monkey(name = "Lars", level = "Land of the Apes", room = "Icicles", address = {"PAL": 0x3E1B66, "NTSC": 0x3E0856}, connection_requirements = {"Icicles from Entry": [["Sky Flyer"], ["*Hard"]], "Icicles from Spa": [["Sky Flyer"], ["*Hard"]], "Icicles from Ski Hill": [["Sky Flyer"], ["*Hard"]]}),
    Monkey(name = "Stone", level = "Land of the Apes", room = "Icicles", address = {"PAL": 0x3E1B65, "NTSC": 0x3E0855}, connection_requirements = {"Icicles from Entry": [["*Attack"], ["Catapult"], ["*Hard"]], "Icicles from Spa": [["*Attack"], ["Catapult"], ["*Hard"]], "Icicles from Ski Hill": [["*Attack"], ["Catapult"], ["*Hard"]]}),
    Monkey(name = "Seb", level = "Land of the Apes", room = "Icicles", address = {"PAL": 0x3E1B68, "NTSC": 0x3E0858}, connection_requirements = {"Icicles from Entry": [[]], "Icicles from Spa": [[]], "Icicles from Ski Hill": [[]]}),
    Monkey(name = "Torvill", level = "Land of the Apes", room = "Icicles", address = {"PAL": 0x3E1B63, "NTSC": 0x3E0853}, connection_requirements = {"Icicles from Entry": [["*Attack"], ["*Hard"]], "Icicles from Spa": [["*Attack"], ["*Hard"]], "Icicles from Ski Hill": [["*Attack"], ["*Hard"]]}),
    Monkey(name = "Dean", level = "Land of the Apes", room = "Icicles", address = {"PAL": 0x3E1B64, "NTSC": 0x3E0854}, connection_requirements = {"Icicles from Entry": [["*Attack"], ["*Hard"]], "Icicles from Spa": [["*Attack"], ["*Hard"]], "Icicles from Ski Hill": [["*Attack"], ["*Hard"]]}),
    Monkey(name = "Monkski", level = "Land of the Apes", room = "Ski Hill", address = {"PAL": 0x3E1B77, "NTSC": 0x3E0867}, connection_requirements = {"Ski Hill from Icicles": [[]]}),
    Monkey(name = "Robinson", level = "Land of the Apes", room = "Ski Hill", address = {"PAL": 0x3E1B76, "NTSC": 0x3E0866}, connection_requirements = {"Ski Hill from Icicles": [[]]}),
    Monkey(name = "Murray", level = "Land of the Apes", room = "Ski Hill", address = {"PAL": 0x3E1B69, "NTSC": 0x3E0859}, connection_requirements = {"Ski Hill from Icicles": [["*Attack"], ["*Hard"]]}),
    Monkey(name = "Linz", level = "Land of the Apes", room = "Ski Hill", address = {"PAL": 0x3E1B75, "NTSC": 0x3E0865}, connection_requirements = {"Ski Hill from Icicles": [[]]}),
    Monkey(name = "Philippe", level = "Land of the Apes", room = "Ski Hill", address = {"PAL": 0x3E1B8B, "NTSC": 0x3E087B}, connection_requirements = {"Ski Hill from Icicles": [[]]}),
    Monkey(name = "Mona", level = "Land of the Apes", address = {"PAL": 0x3E1B6A, "NTSC": 0x3E085A}, connection_requirements = {"Entry from Spawn": [["*Attack"], ["Catapult"], ["*Hard"]], "Entry from Icicles": [["*Attack"], ["Catapult"], ["*Hard"]]}),
    Monkey(name = "Patrick", level = "Land of the Apes", address = {"PAL": 0x3E1B6B, "NTSC": 0x3E085B}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Icicles": [[]]}),

    #The Lost World
    Monkey(name = "Homer", level = "The Lost World", address = {"PAL": 0x3E1B0C, "NTSC": 0x3E07FC}, connection_requirements = {"Entry from Spawn": [["Bananarang"]] ,"Entry from Trees": [["Bananarang", "Water Net"], ["Bananarang", "*Air Crawl"]]}),
    Monkey(name = "Sam", level = "The Lost World", address = {"PAL": 0x3E1B0B, "NTSC": 0x3E07FB}, connection_requirements = {"Entry from Spawn": [[]] ,"Entry from Trees": [["Water Net"], ["*Air Crawl"]]}),
    Monkey(name = "Grant", level = "The Lost World", address = {"PAL": 0x3E1B0E, "NTSC": 0x3E07FE}, connection_requirements = {"Entry from Spawn": [["Sky Flyer", "Water Net"], ["*Air Crawl"], ["*Expert"]] ,"Entry from Trees": [["Sky Flyer", "Water Net"], ["*Air Crawl"], ["Water Net", "*Expert"]]}),
    Monkey(name = "Mervin", level = "The Lost World", address = {"PAL": 0x3E1B0D, "NTSC": 0x3E07FD}, connection_requirements = {"Entry from Spawn": [[]] ,"Entry from Trees": [["Water Net"], ["*Air Crawl"]]}),
    Monkey(name = "Terry", level = "The Lost World", room = "Pterodacytls", address = {"PAL": 0x3E1B11, "NTSC": 0x3E0801}, connection_requirements = {"Pterodactyls from Entry": [["Catapult"], ["*Hard", "Power Punch"], ["*Expert"]], "Pterodactyls from T-Rex": [["Catapult"], ["*Hard", "Power Punch"], ["*Expert"]]}),
    Monkey(name = "Murdoch", level = "The Lost World", room = "Pterodactyls", address = {"PAL": 0x3E1B10, "NTSC": 0x3E0800}, connection_requirements = {"Pterodactyls from Entry": [["*Attack"], ["*Hard"]], "Pterodactyls from T-Rex": [["*Attack"], ["*Hard"]]}),
    Monkey(name = "Monko Polo", level = "The Lost World", room = "Pterodactyls", address = {"PAL": 0x3E1B0F, "NTSC": 0x3E07FF}, connection_requirements = {"Pterodactyls from Entry": [["Sky Flyer"], ["*Hard"], ["*Air Crawl"]], "Pterodactyls from T-Rex": [["Sky Flyer"], ["*Hard"], ["*Air Crawl"]]}),
    Monkey(name = "Emma", level = "The Lost World", room = "Pterodactyls", address = {"PAL": 0x3E1B12, "NTSC": 0x3E0802}, connection_requirements = {"Pterodactyls from Entry": [["Power Punch", "*Hard"], ["*Punch", "Sky Flyer"]], "Pterodactyls from T-Rex": [["Power Punch", "*Hard"], ["*Punch", "Sky Flyer"]]}),
    Monkey(name = "Stumpy", level = "The Lost World", room = "Trees", address = {"PAL": 0x3E1B14, "NTSC": 0x3E0804}, connection_requirements = {"Trees from Entry": [["Water Cannon", "*Hard"], ["*Attack", "Water Cannon"]], "Trees from T-Rex": [["*Hard"], ["*Attack", "Water Cannon"]]}),
    Monkey(name = "Baz", level = "The Lost World", room = "Trees", address = {"PAL": 0x3E1B13, "NTSC": 0x3E0803}, connection_requirements = {"Trees from Entry": [["Water Net"], ["*Hard"]], "Trees from T-Rex": [["Water Net"], ["*Hard"]]}),
    Monkey(name = "Des", level = "The Lost World", room = "Trees", address = {"PAL": 0x3E1B17, "NTSC": 0x3E0807}, connection_requirements = {"Trees from Entry": [["Water Net"], ["*Hard"]], "Trees from T-Rex": [["Water Net"], ["*Hard"]]}),
    Monkey(name = "Christy", level = "The Lost World", room = "Trees", address = {"PAL": 0x3E1B15, "NTSC": 0x3E0805}, connection_requirements = {"Trees from Entry": [["Water Cannon", "*Hard"], ["*Attack", "Water Cannon"]], "Trees from T-Rex": [["*Hard"], ["*Attack", "Water Cannon"]]}),
    Monkey(name = "Stanley", level = "The Lost World", room = "Trees", address = {"PAL": 0x3E1B16, "NTSC": 0x3E0806}, connection_requirements = {"Trees from Entry": [["*Attack", "Water Net"], ["*Hard"]], "Trees from T-Rex": [["*Attack", "Water Net"], ["*Hard"]]}),
    Monkey(name = "Lewis", level = "The Lost World", room = "T-Rex", address = {"PAL": 0x3E1B1C, "NTSC": 0x3E080C}, connection_requirements = {"T-Rex from Trees": [[]], "T-Rex from Pterodactyls": [["Water Net"], ["*Hard"]]}),
    Monkey(name = "Prince", level = "The Lost World", room = "T-Rex", address = {"PAL": 0x3E1B19, "NTSC": 0x3E0809}, connection_requirements = {"T-Rex from Trees": [[]], "T-Rex from Pterodactyls": [["Water Net"], ["*Hard"]]}),
    Monkey(name = "Lunch", level = "The Lost World", room = "T-Rex", address = {"PAL": 0x3E1B1A, "NTSC": 0x3E080A}, connection_requirements = {"T-Rex from Trees": [[]], "T-Rex from Pterodactyls": [["Water Net"], ["*Hard"]]}),
    Monkey(name = "Ovett", level = "The Lost World", room = "T-Rex", address = {"PAL": 0x3E1B18, "NTSC": 0x3E0808}, connection_requirements = {"T-Rex from Trees": [[]], "T-Rex from Pterodactyls": [["Water Net"], ["*Hard"]]}),
    Monkey(name = "Babe", level = "The Lost World", room = "T-Rex", address = {"PAL": 0x3E1B35, "NTSC": 0x3E0825}, connection_requirements = {"T-Rex from Trees": [["Sky Flyer", "R.C. Car", "Water Net"], ["Sky Flyer", "R.C. Car", "*Hard"], ["Sky Flyer", "*Boost Fly", "*Hard"], ["*Air Crawl"]], "T-Rex from Pterodactyls": [["Sky Flyer", "R.C. Car", "Water Net"], ["Sky Flyer", "R.C. Car", "*Hard"], ["Sky Flyer", "*Boost Fly", "*Hard"], ["*Air Crawl"]]}),

    #Red Monkey Battle!
    Monkey(name = "Red Monkey", level = "Red Monkey Battle!", address = {"PAL": 0x3E1BAC, "NTSC": 0x3E089C}, connection_requirements = {"Entry from Spawn": [["*Attack"], ["R.C. Car", "*Hard"], ["Sky Flyer", "*Hard"], ["Bananarang", "*Hard"], ["Catapult", "*Hard"], ["*Expert"]]}),

    #Skyscraper City 
    Monkey(name = "Brendan", level = "Skyscraper City", room = "Final Room", address = {"PAL": 0x3E1B91, "NTSC": 0x3E0881}, connection_requirements = {"Final Room from Tank": [[]]}),
    Monkey(name = "Ali", level = "Skyscraper City", room = "Final Room", address = {"PAL": 0x3E1B90, "NTSC": 0x3E0880}, connection_requirements = {"Final Room from Tank": [["Catapult"], ["Sky Flyer", "*Hard"]]}),
    Monkey(name = "Jim  ", level = "Skyscraper City", room = "Final Room", address = {"PAL": 0x3E1B2C, "NTSC": 0x3E081C}, connection_requirements = {"Final Room from Tank": [["*Punch", "Electro Magnet", "Catapult", "R.C. Car"], ["*Punch", "Electro Magnet", "Catapult", "Sky Flyer", "*Expert", "*Boost Fly"], ["*Punch", "*Air Crawl"]]}), #Why are there three Jims in this game
    Monkey(name = "Ricardo", level = "Skyscraper City", room = "Final Room", address = {"PAL": 0x3E1B92, "NTSC": 0x3E0882}, connection_requirements = {"Final Room from Tank": [["Electro Magnet", "Catapult", "R.C. Car"], ["Electro Magnet", "Catapult", "Sky Flyer", "*Expert", "*Boost Fly"], ["*Air Crawl"]]}),
    Monkey(name = "Douglas", level = "Skyscraper City", room = "Final Room", address = {"PAL": 0x3E1B8F, "NTSC": 0x3E087F}, connection_requirements = {"Final Room from Tank": [["Sky Flyer"], ["*Hard"]]}),
    Monkey(name = "Cameron", level = "Skyscraper City", room = "Final Room", address = {"PAL": 0x3E1B8E, "NTSC": 0x3E087E}, connection_requirements = {"Final Room from Tank": [[]]}),    
    Monkey(name = "Slider", level = "Skyscraper City", address = {"PAL": 0x3E1B22, "NTSC": 0x3E0812}, connection_requirements = {"Entry from Spawn": [["Electro Magnet"], ["*Air Crawl"], ["Sky Flyer", "*Hard"]], "Entry from Lobby": [[]]}),
    Monkey(name = "Spank", level = "Skyscraper City", address = {"PAL": 0x3E1B21, "NTSC": 0x3E0811}, connection_requirements = {"Entry from Spawn": [["Electro Magnet"], ["*Air Crawl"], ["Sky Flyer", "*Hard"]], "Entry from Lobby": [[]]}),
    Monkey(name = "Din", level = "Skyscraper City", address = {"PAL": 0x3E1B20, "NTSC": 0x3E0810}, connection_requirements = {"Entry from Spawn": [["Electro Magnet"], ["*Air Crawl"], ["Sky Flyer", "*Hard"]], "Entry from Lobby": [[]]}),
    Monkey(name = "Sue", level = "Skyscraper City", address = {"PAL": 0x3E1B1F, "NTSC": 0x3E080F}, connection_requirements = {"Entry from Spawn": [["Electro Magnet"], ["*Air Crawl"], ["Sky Flyer", "*Hard"]], "Entry from Lobby": [[]]}),
    Monkey(name = "Dum Dum", level = "Skyscraper City", address = {"PAL": 0x3E1B1E, "NTSC": 0x3E080E}, connection_requirements = {"Entry from Spawn": [["Electro Magnet"], ["*Air Crawl"], ["Sky Flyer", "*Hard"]], "Entry from Lobby": [[]]}),
    Monkey(name = "Jitter", level = "Skyscraper City", address = {"PAL": 0x3E1B1D, "NTSC": 0x3E080D}, connection_requirements = {"Entry from Spawn": [["Electro Magnet", "*Attack"], ["*Air Crawl", "*Attack"], ["*Air Crawl", "*Hard"], ["Electro Magnet", "*Hard"], ["Sky Flyer", "*Hard"]], "Entry from Lobby": [["*Attack"], ["*Hard"]]}),
    Monkey(name = "Robson", level = "Skyscraper City", room = "Lobby", address = {"PAL": 0x3E1B27, "NTSC": 0x3E0817}, connection_requirements = {"Lobby from Entry": [[]], "Lobby from Sewer": [[]], "Lobby from Lobby Corridor": [[]], "Lobby from Final Room": [[]]}),
    Monkey(name = "Spud II", level = "Skyscraper City", room = "Lobby", address = {"PAL": 0x3E1B26, "NTSC": 0x3E0816}, connection_requirements = {"Lobby from Entry": [[]], "Lobby from Sewer": [[]], "Lobby from Lobby Corridor": [[]], "Lobby from Final Room": [[]]}),
    Monkey(name = "Cole", level = "Skyscraper City", room = "Lobby", address = {"PAL": 0x3E1B24, "NTSC": 0x3E0814}, connection_requirements = {"Lobby from Entry": [["Sky Flyer"], ["*Air Crawl", "*Hard"]], "Lobby from Sewer": [["Sky Flyer"], ["*Air Crawl", "*Hard"]], "Lobby from Lobby Corridor": [["Sky Flyer"], ["*Air Crawl", "*Hard"]], "Lobby from Final Room": [["Sky Flyer"], ["*Air Crawl", "*Hard"]]}),
    Monkey(name = "Ty ", level = "Skyscraper City", room = "Lobby", address = {"PAL": 0x3E1B28, "NTSC": 0x3E0818}, connection_requirements = {"Lobby Corridor from Sewer": [["*Attack"], ["*Hard"]], "Lobby Corridor from Tank": [["*Attack"], ["*Hard"]]}),
    Monkey(name = "Slacker", level = "Skyscraper City", room = "Sewer", address = {"PAL": 0x3E1B2A, "NTSC": 0x3E081A}, connection_requirements = {"Sewer from Lobby": [["Electro Magnet"]], "Sewer from Lobby Corridor": [["Electro Magnet", "R.C. Car"], ["*Air Crawl", "*Expert"]]}),
    Monkey(name = "Kengo", level = "Skyscraper City", room = "Sewer", address = {"PAL": 0x3E1B2B, "NTSC": 0x3E081B}, connection_requirements = {"Sewer from Lobby": [["Electro Magnet", "R.C. Car"]], "Sewer from Lobby Corridor": [["R.C. Car", "Electro Magnet"], ["*Air Crawl", "*Expert"]]}),
    Monkey(name = "Rory", level = "Skyscraper City", room = "Sewer", address = {"PAL": 0x3E1B23, "NTSC": 0x3E0813}, connection_requirements = {"Sewer from Lobby": [["Electro Magnet", "R.C. Car", "*Punch"]], "Sewer from Lobby Corridor": [["R.C. Car", "Electro Magnet", "*Punch"], ["*Air Crawl", "*Punch", "*Expert"]]}),
    Monkey(name = "Eubank", level = "Skyscraper City", room = "Sewer", address = {"PAL": 0x3E1B2D, "NTSC": 0x3E081D}, connection_requirements = {"Sewer from Lobby": [["Electro Magnet", "R.C. Car", "Bananarang", "Water Net"]], "Sewer from Lobby Corridor": [["R.C. Car", "Electro Magnet", "Bananarang", "Water Net"], ["*Air Crawl", "Bananarang", "*Expert"]]}),
    Monkey(name = "Miller", level = "Skyscraper City", room = "Sewer", address = {"PAL": 0x3E1B2E, "NTSC": 0x3E081E}, connection_requirements = {"Sewer from Lobby": [["Electro Magnet", "R.C. Car", "Sky Flyer", "Water Net"], ["Electro Magnet", "R.C. Car", "Sky Flyer", "*Hard"], ["Electro Magnet", "R.C. Car", "*Hard", "Water Net"], ["Electro Magnet", "R.C. Car", "*Air Crawl", "*Hard"], ["Electro Magnet", "R.C. Car", "Dash Hoop", "*Long Jump", "*Expert"]], "Sewer from Lobby Corridor": [["Water Net", "Sky Flyer"], ["Water Net", "*Hard"], ["Sky Flyer", "*Hard"], ["*Air Crawl", "*Hard"], ["Dash Hoop", "*Expert", "*Long Jump"]]}),
    Monkey(name = "Spacey", level = "Skyscraper City", room = "Tank", address = {"PAL": 0x3E1B8C, "NTSC": 0x3E087C}, connection_requirements = {"Tank from Lobby Corridor": [["*UFO", "Dash Hoop"], ["*UFO", "Sky Flyer", "*Hard"], ["*UFO", "*Air Crawl", "*Hard"]], "Tank from Final Room": [["*UFO", "Dash Hoop"], ["*UFO", "Sky Flyer", "*Hard"], ["*UFO", "*Air Crawl", "*Hard"]]}),
    Monkey(name = "Ivor", level = "Skyscraper City", room = "Tank", address = {"PAL": 0x3E1B8D, "NTSC": 0x3E087D}, connection_requirements = {"Tank from Lobby Corridor": [[]], "Tank from Final Room": [[]]}),

    #Code C.H.I.M.P. - continue logic from here
    Monkey(name = "Kiki", level = "Code C.H.I.M.P.", address = {"PAL": 0x3E1B3F, "NTSC": 0x3E082F}, connection_requirements = {"Entry from Spawn": [["*UFO"]], "Entry from Base Entrance": [["*UFO", "*Air Crawl"]], "Entry from Moving Platforms": [["*UFO"]]}),
    Monkey(name = "Cole ", level = "Code C.H.I.M.P.", address = {"PAL": 0x3E1B3D, "NTSC": 0x3E082D}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Base Entrance": [["*Air Crawl"]], "Entry from Moving Platforms": [[]]}),
    Monkey(name = "Mimi", level = "Code C.H.I.M.P.", address = {"PAL": 0x3E1B3E, "NTSC": 0x3E082E}, connection_requirements = {"Entry from Spawn": [["*UFO"]], "Entry from Base Entrance": [["*UFO", "*Air Crawl"]], "Entry from Moving Platforms": [["*UFO"]]}),
    Monkey(name = "Tanjobi", level = "Code C.H.I.M.P.", address = {"PAL": 0x3E1B3B, "NTSC": 0x3E082B}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Base Entrance": [["*Air Crawl"]], "Entry from Moving Platforms": [[]]}),
    Monkey(name = "Major", level = "Code C.H.I.M.P.", address = {"PAL": 0x3E1B3C, "NTSC": 0x3E082C}, connection_requirements = {"Entry from Spawn": [[]], "Entry from Base Entrance": [["*Air Crawl"]], "Entry from Moving Platforms": [[]]}),
    Monkey(name = "Ebiike", level = "Code C.H.I.M.P.", address = {"PAL": 0x3E1B41, "NTSC": 0x3E0831}, connection_requirements = {"Entry from Spawn": [["*Gear"]], "Entry from Base Entrance": [[]], "Entry from Moving Platforms": [["*Gear"]]}),
    Monkey(name = "Corporal", level = "Code C.H.I.M.P.", room = "Base Entrance", address = {"PAL": 0x3E1B44, "NTSC": 0x3E0834}, connection_requirements = {"Base Entrance from Entry": [[]], "Base Entrance from Tank": [[]]}),
    Monkey(name = "Sloth", level = "Code C.H.I.M.P.", room = "Base Entrance", address = {"PAL": 0x3E1B43, "NTSC": 0x3E0833}, connection_requirements = {"Base Entrance from Entry": [["Catapult"]], "Base Entrance from Tank": [["Catapult"]]}),
    Monkey(name = "Heston", level = "Code C.H.I.M.P.", room = "Base Entrance", address = {"PAL": 0x3E1B45, "NTSC": 0x3E0835}, connection_requirements = {"Base Entrance from Entry": [[]], "Base Entrance from Tank": [[]]}),
    Monkey(name = "Buzz", level = "Code C.H.I.M.P.", room = "Base Entrance", address = {"PAL": 0x3E1B42, "NTSC": 0x3E0832}, connection_requirements = {"Base Entrance from Entry": [["*Punch"]], "Base Entrance from Tank": [["*Punch"]]}),
    Monkey(name = "Matt", level = "Code C.H.I.M.P.", room = "Treadmills", address = {"PAL": 0x3E1B4A, "NTSC": 0x3E083A}, connection_requirements = {"Treadmills from Tank": [["Electro Magnet"], ["Sky Flyer", "*Boost Fly", "*Expert"], ["*Air Crawl", "*Hard"]], "Treadmills from Moving Platforms": [[]]}),
    Monkey(name = "Gaelle", level = "Code C.H.I.M.P.", room = "Treadmills", address = {"PAL": 0x3E1B4B, "NTSC": 0x3E083B}, connection_requirements = {"Treadmills from Tank": [["Electro Magnet"], ["Sky Flyer", "*Boost Fly", "*Expert"], ["*Air Crawl", "*Hard"]], "Treadmills from Moving Platforms": [[]]}),
    Monkey(name = "Arnold", level = "Code C.H.I.M.P.", room = "Moving Platforms", address = {"PAL": 0x3E1B6C, "NTSC": 0x3E085C}, connection_requirements = {"Moving Platforms from Magnetic Panels End": [["*Attack"], ["*Hard"]]}),
    Monkey(name = "Sylvester", level = "Code C.H.I.M.P.", room = "Moving Platforms", address = {"PAL": 0x3E1B6D, "NTSC": 0x3E085D}, connection_requirements = {"Moving Platforms from Magnetic Panels End": [["*Attack"], ["*Hard"]]}),
    Monkey(name = "Sandra", level = "Code C.H.I.M.P.", room = "Moving Platforms", address = {"PAL": 0x3E1B6E, "NTSC": 0x3E085E}, connection_requirements = {"Moving Platforms from Magnetic Panels End": [["*Attack"], ["*Hard"]]}),
    Monkey(name = "Boots", level = "Code C.H.I.M.P.", room = "Moving Platforms", address = {"PAL": 0x3E1B71, "NTSC": 0x3E0861}, connection_requirements = {"Moving Platforms from Magnetic Panels End": [["*Attack"], ["*Hard"]], "Moving Platforms from Entry": [[]]}),
    Monkey(name = "Sinclair", level = "Code C.H.I.M.P.", room = "Magnetic Panels", address = {"PAL": 0x3E1B6F, "NTSC": 0x3E085F}, connection_requirements = {"Magnetic Panels Start from Moving Platforms": [["Electro Magnet", "Sky Flyer"], ["Electro Magnet", "*Hard", "Pipotchi"], ["*Boost Fly", "*Hard", "Power Punch"]], "Magnetic Panels End from Moving Platforms": [["Electro Magnet", "Sky Flyer"], ["Electro Magnet", "*Hard", "Pipotchi"], ["*Boost Fly", "*Hard", "Power Punch"]]}),
    Monkey(name = "Keeble", level = "Code C.H.I.M.P.", room = "Magnetic Panels", address = {"PAL": 0x3E1B70, "NTSC": 0x3E0860}, connection_requirements = {"Magnetic Panels Start from Moving Platforms": [["Electro Magnet", "Sky Flyer", "*Attack"], ["Electro Magnet", "Sky Flyer", "*Hard"], ["Electro Magnet", "*Hard", "Pipotchi"], ["*Boost Fly", "*Hard", "Power Punch"]], "Magnetic Panels End from Moving Platforms": [["Electro Magnet", "Sky Flyer", "*Attack"], ["Electro Magnet", "Sky Flyer", "*Hard"], ["Electro Magnet", "*Hard", "Pipotchi"], ["*Boost Fly", "*Hard", "Power Punch"]]}),
    Monkey(name = "General", level = "Code C.H.I.M.P.", room = "Tank", address = {"PAL": 0x3E1B46, "NTSC": 0x3E0836}, connection_requirements = {"Tank from Base Entrance": [[]], "Tank from Treadmills": [[]]}),
    Monkey(name = "Laura", level = "Code C.H.I.M.P.", room = "Tank", address = {"PAL": 0x3E1B48, "NTSC": 0x3E0838}, connection_requirements = {"Tank from Base Entrance": [[]], "Tank from Treadmills": [[]]}),
    Monkey(name = "The Cleaner", level = "Code C.H.I.M.P.", room = "Tank", address = {"PAL": 0x3E1B47, "NTSC": 0x3E0837}, connection_requirements = {"Tank from Base Entrance": [[]], "Tank from Treadmills": [[]]}),

    #Giant Yellow Monkey Battle!
    Monkey(name = "Yellow Monkey ", level = "Giant Yellow Monkey Battle!", address = {"PAL": 0x3E1BAD, "NTSC": 0x3E089D}, connection_requirements = {"Entry from Spawn": [["Stun Club"], ["Power Punch"], ["Sky Flyer", "*Hard"], ["Catapult", "*Hard"], ["*Expert"]]}),

    #Moon Base
    Monkey(name = "Lardy", level = "Moon Base", room = "Wheel", address = {"PAL": 0x3E1B2F, "NTSC": 0x3E081F}, connection_requirements = {"Wheel from Entry": [["*Gear"], ["*Air Crawl"], ["*Boost Fly", "*Long Jump", "*Expert"]]}),
    Monkey(name = "Tom", level = "Moon Base", room = "Robot", address = {"PAL": 0x3E1B1B, "NTSC": 0x3E080B}, connection_requirements = {"Robot from Entry": [["*Radar", "*Attack"], ["*Hard"]]}),
    Monkey(name = "Bruce", level = "Moon Base", room = "Magnetic Panels", address = {"PAL": 0x3E1B7F, "NTSC": 0x3E086F}, connection_requirements = {"Magnetic Panels from Mech Arena": [[]], "Magnetic Panels from Moving Platforms": [["Electro Magnet"], ["*Air Crawl"], ["*Boost Fly", "*Hard"]]}),
    Monkey(name = "Han", level = "Moon Base", room = "Mech Arena", address = {"PAL": 0x3E1B7E, "NTSC": 0x3E086E}, connection_requirements = {"Mech Arena from Magnetic Panels": [[]], "Mech Arena from Entry": [[]]}),
    Monkey(name = "Neil Apestrong", level = "Moon Base", address = {"PAL": 0x3E1B72, "NTSC": 0x3E0862}, connection_requirements = {"Entry from Mech Arena": [["*Attack"], ["*Hard"]], "Entry from Inside Climb": [["*Attack"], ["*Hard"]], "Entry from Spawn": [["*Air Crawl", "*Attack"], ["*Air Crawl", "*Hard"]], "Entry from Wheel": [["*Air Crawl", "*Attack"], ["*Air Crawl", "*Hard"]], "Entry from UFO Arena": [["*Air Crawl", "*Attack"], ["*Air Crawl", "*Hard"]], "Entry from Armoured Monkey Arena": [["*Air Crawl", "*Attack"], ["*Air Crawl", "*Hard"]], "Entry from Robot": [["*Air Crawl", "*Attack"], ["*Air Crawl", "*Hard"]], "Entry from Moving Platforms": [["*Air Crawl", "*Attack"], ["*Air Crawl", "*Hard"]], "Entry from Bomb": [["*Air Crawl", "*Attack"], ["*Air Crawl", "*Hard"]]}),
    Monkey(name = "Chelsea", level = "Moon Base", address = {"PAL": 0x3E1B7B, "NTSC": 0x3E086B}, connection_requirements = {"Entry from Mech Arena": [["*Air Crawl"]], "Entry from Inside Climb": [["*Air Crawl"]], "Entry from Spawn": [[]], "Entry from Wheel": [[]], "Entry from UFO Arena": [[]], "Entry from Armoured Monkey Arena": [["*Air Crawl"]], "Entry from Robot": [["*Air Crawl"]], "Entry from Moving Platforms": [["*Air Crawl"]], "Entry from Bomb": [[]]}),
    Monkey(name = "SAL-01", level = "Moon Base", room = "Rotating Magnets", address = {"PAL": 0x3E1B40, "NTSC": 0x3E0830}, connection_requirements = {"Rotating Magnets from UFO Arena": [["*Attack"], ["Catapult", "*Hard"], ["*Expert"]], "Rotating Magnets from Armoured Monkey Arena": [["Electro Magnet", "*Attack"], ["Electro Magnet", "Catapult", "*Hard"], ["Electro Magnet", "Hard"], ["*Air Crawl", "*Attack"], ["*Air Crawl"]]}),
    Monkey(name = "Kubrick", level = "Moon Base", address = {"PAL": 0x3E1AD6, "NTSC": 0x3E07C6}, connection_requirements = {"Rotating Magnets from UFO Arena": [["Electro Magnet", "Sky Flyer", "Catapult"], ["Electro Magnet", "*Hard"], ["*Air Crawl"]], "Rotating Magnets from Armoured Monkey Arena": [["Catapult"], ["*Hard"]]}),
    Monkey(name = "Chewy", level = "Moon Base", address = {"PAL": 0x3E1B7C, "NTSC": 0x3E086C}, connection_requirements = {"Rotating Magnets from UFO Arena": [["Electro Magnet", "Sky Flyer"], ["Electro Magnet", "*Hard"], ["*Air Crawl"]], "Rotating Magnets from Armoured Monkey Arena": [[]]}),
    Monkey(name = "Obi Ook Kenobi", level = "Moon Base", room = "Moving Platforms", address = {"PAL": 0x3E1AD9, "NTSC": 0x3E07C9}, connection_requirements = {"Moving Platforms from Entry": [["*Moon Fire"]], "Moving Platforms from Magnetic Panels": [["Electro Magnet"], ["*Air Crawl"]]}),
    Monkey(name = "Darth Apester", level = "Moon Base", room = "Moving Platforms", address = {"PAL": 0x3E1AE2, "NTSC": 0x3E07D2}, connection_requirements = {"Moving Platforms from Entry": [["*Moon Fire"]], "Moving Platforms from Magnetic Panels": [["Electro Magnet"], ["*Air Crawl"]]}),
    Monkey(name = "Luke Apewalker", level = "Moon Base", room = "Moving Platforms", address = {"PAL": 0x3E1AFB, "NTSC": 0x3E07EB}, connection_requirements = {"Moving Platforms from Entry": [["Electro Magnet", "*Moon Fire"], ["*Moon Fire", "*Boost Fly", "*Expert"], ["*Air Crawl"]], "Moving Platforms from Magnetic Panels": [[]]}),
    Monkey(name = "Neo", level = "Moon Base", room = "Inside Climb", address = {"PAL": 0x3E1B38, "NTSC": 0x3E0828}, connection_requirements = {"Inside Climb from Entry": [["Sky Flyer"], ["*Hard"], ["*Air Crawl"]], "Inside Climb from Outside Climb Start": [["Sky Flyer"], ["*Hard"], ["*Air Crawl"]], "Inside Climb from Outside Climb End": [["Sky Flyer"], ["*Hard"], ["*Air Crawl"]], "Inside Climb from Bomb": [["Sky Flyer"], ["*Hard"], ["*Air Crawl"]]}),
    Monkey(name = "Tsubasa", level = "Moon Base", room = "Inside Climb", address = {"PAL": 0x3E1AA0, "NTSC": 0x3E0790}, connection_requirements = {"Inside Climb from Entry": [[]], "Inside Climb from Outside Climb Start": [[]], "Inside Climb from Outside Climb End": [[]], "Inside Climb from Bomb": [[]]}),
    Monkey(name = "Boba", level = "Moon Base", room = "Inside Climb", address = {"PAL": 0x3E1B29, "NTSC": 0x3E0819}, connection_requirements = {"Inside Climb from Entry": [["*Air Crawl"]], "Inside Climb from Outside Climb Start": [["*Air Crawl"]], "Inside Climb from Outside Climb End": [["Sky Flyer"], ["*Air Crawl"]], "Inside Climb from Bomb": [["Sky Flyer"], ["*Air Crawl"]]}),
    Monkey(name = "Lister", level = "Moon Base", room = "Inside Climb", address = {"PAL": 0x3E1B49, "NTSC": 0x3E0839}, connection_requirements = {"Inside Climb from Entry": [["*Air Crawl", "*Punch"]], "Inside Climb from Outside Climb Start": [["*Air Crawl", "*Punch"]], "Inside Climb from Outside Climb End": [["Sky Flyer", "*Punch"], ["*Air Crawl", "*Punch"]], "Inside Climb from Bomb": [["Sky Flyer", "*Punch"], ["*Air Crawl", "*Punch"]]}),
    Monkey(name = "G. Ookas", level = "Moon Base", room = "UFO Arena", address = {"PAL": 0x3E1ADB, "NTSC": 0x3E07CB}, connection_requirements = {"UFO Arena from Entry": [["*UFO"], ["*Expert"]], "UFO Arena from Rotating Magnets": [["*UFO"], ["*Expert"]]}),
    Monkey(name = "Scully", level = "Moon Base", room = "UFO Arena", address = {"PAL": 0x3E1ADA, "NTSC": 0x3E07CA}, connection_requirements = {"UFO Arena from Entry": [["*UFO"], ["*Expert"]], "UFO Arena from Rotating Magnets": [["*UFO"], ["*Expert"]]}),   
    Monkey(name = "Kai", level = "Moon Base", room = "Armoured Monkey Arena", address = {"PAL": 0x3E1B7D, "NTSC": 0x3E086D}, connection_requirements = {"Armoured Monkey Arena from Rotating Magnets": [["*Attack"], ["Catapult", "*Hard"], ["*Expert"]], "Armoured Monkey Arena from Entry": [["*Attack"], ["Catapult", "*Hard"], ["*Expert"]]}),
    Monkey(name = "Yoshi", level = "Moon Base", room = "Armoured Monkey Arena", address = {"PAL": 0x3E1ADC, "NTSC": 0x3E07CC}, connection_requirements = {"Armoured Monkey Arena from Rotating Magnets": [["*Attack"], ["*Expert"]], "Armoured Monkey Arena from Entry": [["*Attack"], ["Catapult", "*Hard"], ["*Expert"]]}),

    #Showdown with Specter!
    Monkey(name = "Specter", level = "Showdown with Specter!", connection_requirements = {"Entry from Spawn": [["Electro Magnet", "Stun Club", "Sky Flyer", "Dash Hoop"], ["Electro Magnet", "Power Punch", "Sky Flyer", "Dash Hoop"], ["Electro Magnet", "*Attack", "*Hard"], ["Electro Magnet", "R.C. Car", "*Hard"], ["Electro Magnet", "Bananarang", "*Hard"], ["Electro Magnet", "Sky Flyer", "*Hard"], ["Electro Magnet", "Catapult", "*Hard"], ["Electro Magnet", "*Expert"]]}),

    #Final Showdown with Specter!
    Monkey(name = "Specter ", level = "Final Showdown with Specter!", address = {"PAL": 0x3E1BAE, "NTSC": 0x3E089E}, connection_requirements = {"Entry from Spawn": [["*Attack"], ["R.C. Car", "*Hard"], ["Bananarang", "*Hard"], ["Sky Flyer", "*Hard"], ["Catapult", "*Hard"], ["*Expert"]]})
]

for i in range(0, len(monkeys)):
    monkeys[i].id = i + 1
            
monkey_from_name: dict[str, Monkey] = {monkey.name: monkey for monkey in monkeys}
monkey_from_id: dict[int, Monkey] = {monkey.id: monkey for monkey in monkeys}